### ISSUE TITLE
【v1.0.0】无法删除文件

### ISSUE THREAD

**Issue by RoyRao2333** [tw93/MiaoYan#100]
刚开始使用这款App，各方面都很吸引我，感谢开发者的努力！

刚想删除文件的时候，不管是单个文件还是多选文件，右键删除或者Cmd + ←，都没有任何反应，iCloud文件夹里的那些文件也没有被移到Trash里，不知道是不是Bug呢？谢谢！

**Comment by tw93** [comment]
我测试了一下是可以的，可能有一个情况，是你打开了预览模式，在预览模式下防止用户误触，将删除给过滤了
可以command+3到编辑模式，然后试试

**Comment by RoyRao2333** [comment]
> 我测试了一下是可以的，可能有一个情况，是你打开了预览模式，在预览模式下防止用户误触，将删除给过滤了 可以command+3到编辑模式，然后试试

谢谢！用cmd + 3切换后确实可以删除了，但是我第一次也切换到了编辑模式，只不过是点的眼睛图标切换的，那一次就无法删除。不知道是不是眼睛图标的某些判断有Bug呢？我好像复现不出来了，有空的话希望复查一下哦。

无论如何，感谢开发这么优秀的一款编辑器，期待今后的更新！

**Comment by tw93** [comment]
好勒 谢谢反馈我优化一下

**Comment by tw93** [comment]
正式版本已经发布，🐶解决了预览不能删除掉的特性，可去更新1.1.0 ~
https://github.com/tw93/MiaoYan/releases/tag/V1.1.0

**Comment by RoyRao2333** [comment]
> 正式版本已经发布，🐶解决了预览不能删除掉的特性，可去更新1.1.0 ~ https://github.com/tw93/MiaoYan/releases/tag/V1.1.0

好的！感谢开发大大的努力~
