### ISSUE TITLE
两个行内代码块内的下划线被识别为斜体记号，导致颜色混乱

### ISSUE THREAD

**Issue by shellRaining** [tw93/MiaoYan#101]
如图
<img width="390" alt="image" src="https://user-images.githubusercontent.com/72488394/181664014-67ae9d7f-1a99-4635-8b84-38d0fd064642.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/72488394/181664046-faa29d2a-3a64-4e43-bf5b-9a326975d5c2.png">
其他标签也有这个问题，比如加粗和斜体的另一种写法

希望可以各种格式的文本有不同的颜色，这样会好分辨一些（也有可能会让界面花里胡哨的，起了反作用(◕ˇ∀ˇ◕。)）

**Comment by tw93** [comment]
是的 其实当时我有意识到这个点，尽量克制中，这个让我想一想怎么更加好一些

**Comment by tw93** [comment]
想了想，暂时先这样好了，今天试了试因为不同的颜色会更奇怪，等哪天有好解法，我会来回复这边issue
