### ISSUE TITLE
【feat】TODO List 在预览模式下无法点击更改状态

### ISSUE THREAD

**Issue by RoyRao2333** [tw93/MiaoYan#102]
你好大大~

在一天的使用下来，发现MiaoYan真的很不错！

目前发现一个问题就是，TODO List在预览模式下不能勾选和取消勾选，这个应该是很重要的feature哦~希望大大在今后的版本中优化一下，感激不尽！

**Comment by tw93** [comment]
谢谢反馈，已经加入到下一个版本的计划中，的确这个做好了，可以方便不少

**Comment by tw93** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/8736212/181924874-c78f0df4-1138-4fb7-9758-814c2c652908.gif)
代码已OK，放到最近的一个版本

**Comment by RoyRao2333** [comment]
> ![ScreenFlow](https://user-images.githubusercontent.com/8736212/181924874-c78f0df4-1138-4fb7-9758-814c2c652908.gif) [ ![ScreenFlow](https://user-images.githubusercontent.com/8736212/181924874-c78f0df4-1138-4fb7-9758-814c2c652908.gif) ](https://user-images.githubusercontent.com/8736212/181924874-c78f0df4-1138-4fb7-9758-814c2c652908.gif) [ ](https://user-images.githubusercontent.com/8736212/181924874-c78f0df4-1138-4fb7-9758-814c2c652908.gif) 代码已OK，放到最近的一个版本

非常感谢大大😍期待这款软件越来越好

**Comment by tw93** [comment]
辛苦去更新，1.1.1，直接点击妙言菜单栏检查更新即可~

**Comment by RoyRao2333** [comment]
> 辛苦去更新，1.1.1，直接点击妙言菜单栏检查更新即可~

感谢大大～
