### ISSUE TITLE
编辑默认文档会不断生成副本

### ISSUE THREAD

**Issue by yiliang114** [tw93/MiaoYan#103]
![image](https://user-images.githubusercontent.com/11473889/181674412-26ed3149-933b-4a20-910d-20330786a35a.png)

刚刚下载安装, 随手编辑了一下默认的文档，保存之后发现会不断生成副本。 这个符合预期吗？

**Comment by tw93** [comment]
谢谢反馈，这个我看看

**Comment by tw93** [comment]
不是特别好复现，方便录制一个视频吗

**Comment by yiliang114** [comment]
早上尝试复现了一下，卸载了重装，把 `/Library/Mobile Documents/iCloud~com~tw93~miaoyan/Document` 下文件都清空后再看，发现也复现不出来了。 按理说应该也不是误触了 cmd + d 复制文档导致的，因为我看这种情况下生成的文件自带时间的后缀，而这个 issue 第一张截图中的副本后缀名是 2, 3, 4

![image](https://user-images.githubusercontent.com/11473889/181876824-9742f3ec-25cf-4f68-ae95-7e71b8231246.png)

**Comment by tw93** [comment]
超级感谢反馈，这个问题有些奇怪了，不过概率有些低
这样我这边也持续使用着，假如复现了修复，我来回复这个issue，先关闭了

**Comment by yiliang114** [comment]
> 超级感谢反馈，这个问题有些奇怪了，不过概率有些低 这样我这边也持续使用着，假如复现了修复，我来回复这个issue，先关闭了

好滴
