### ISSUE TITLE
homebrew install failed

### ISSUE THREAD

**Issue by faimin** [tw93/MiaoYan#105]
```ruby
Error: miaoyan: Download failed on Cask 'miaoyan' with message: Download failed: 
https://github.com/tw93/MiaoYan/releases/download/V1.1.0/MiaoYan.dmg
```

下载地址不对，真实的版本号是`v1.1.1`，链接为 [https://github.com/tw93/MiaoYan/releases/download/V1.1.1/MiaoYan.dmg](https://github.com/tw93/MiaoYan/releases/download/V1.1.1/MiaoYan.dmg)， 而`homebrew` [#128781](https://github.com/Homebrew/homebrew-cask/pull/128781/files) 中的下载链接版本号写的是`v1.1.0` 。

**Comment by tw93** [comment]
我的锅，辛苦先通过下载的方式来弄
另外 brew安装的好处是 我一直觉得很慢

**Comment by faimin** [comment]
是的，在国内确实很慢，因为是用`github`来管理源嘛，不过可以通过替换镜像来缓解这个问题。我用`homebrew`主要是图它的便利性，用它管理软件的升级、卸载很方便。

**Comment by tw93** [comment]
好的 了解啦 预计下一个版本就好了
