### ISSUE TITLE
一些bug和一点小建议

### ISSUE THREAD

**Issue by nerocho** [tw93/MiaoYan#107]
版本：1.1.1

感谢作者的开源精神，我在使用时总会遇到应用闪退，每次闪退大多都发生在写有序列表时，例如下面：
```markdown
## 写着写着就会卡主，然后就闪退了

1. foo
2. foo
  1. bar
  2. bar
```

下面是一些小建议：

1. 增加文章内的搜索，目前cmd+f 是搜索文件名
2. 能插入图片已经很意外了，很棒的功能，如果能在删除文章or删除文章内容（该内容包含图片）时，能顺带把`i`目录下的图片给删了就好了

**Comment by tw93** [comment]
你的系统版本是？

**Comment by nerocho** [comment]
不好意思，大意了
<img width="478" alt="image" src="https://user-images.githubusercontent.com/7479275/182325238-7441b6b4-bdee-4689-80ef-2a40a48769b6.png">

**Comment by tw93** [comment]
还想请教一下你用的是苹果原生输入法吗 还是？

**Comment by nerocho** [comment]
搜狗输入法
<img width="241" alt="image" src="https://user-images.githubusercontent.com/7479275/182493772-0750c797-394b-4966-9a05-f2636e05bf51.png">

**Comment by nerocho** [comment]
就比如这样，写着写着回车后字没有到编辑器中（但其实已经到了），然后切换下view 模式就有了，再切回来就好了，一般出现这种情况后，再出现就会大概率闪退

这个是敲着敲着，字就不落在编辑器中了
<img width="969" alt="WX20220803-095710@2x" src="https://user-images.githubusercontent.com/7479275/182507797-b27300e5-9cd1-4a9a-bd22-2a97d93cd718.png">
切换后就有字了
<img width="1006" alt="WX20220803-095721@2x" src="https://user-images.githubusercontent.com/7479275/182507838-367d468f-7633-494c-97f2-119b6f7aa8ac.png">

**Comment by tw93** [comment]
我大概知道问题所在了，辛苦试试这个包，[下载替换一下](https://gw.alipayobjects.com/os/k/3dwqam/MiaoYan%2525202022-08-03%25252020-05-04.zip)
麻烦多试几下

**Comment by nerocho** [comment]
🐂🍺 好像闪退那个问题好了，目前一切正常。
然后内容的搜索，可能是我表达不力，其实只需要一个单markdown的查找替换就好了，比如：批量替换一些之前写的关键字啥的。
不过现在这个搜索我觉得也挺好用，直接搜索所有文档的内容好像更方便，不用特意去打开某个文档搜索。好像现在连个模式是混合的？ 我`cmd+f` 搜索`服务`如下：
前四个md只有标题包含服务，后两个md只有内容包含服务（当点击对应标题，内容会高亮好评）
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/7479275/182748169-bf0fd536-5224-4130-8dfa-a7e8c32a8e42.png">

**Comment by tw93** [comment]
@nerocho 很感谢帮忙测试和反馈哈，我这边很需要大伙对于妙言的建议，你说的文章搜索可以看这里
由于这个功能属于NSTextView自带的，我只是加了一下引用，也能满足使用
![image](https://user-images.githubusercontent.com/8736212/182750756-b91ec949-1fdb-4334-a0d8-5019f4856fdf.png)
这个issue我先关闭，欢迎后续使用过程中有任何建议直接issue或者twitter找我都行哈
