### ISSUE TITLE
宝子 左侧的目录可以做成tree的形式嘛? 现在文件夹层级都被拍平了

### ISSUE THREAD

**Issue by qsjc** [tw93/MiaoYan#109]

**Comment by tw93** [comment]
正常有几层？

**Comment by qsjc** [comment]
![Snipaste_2022-08-05_09-49-42.png](https://s2.loli.net/2022/08/05/U39CRQwFEYatdJg.png)

**Comment by tw93** [comment]
其实更好的简洁方式可以调整一下目录分类

**Comment by tw93** [comment]
这个功能暂时应该没有计划支持，因为我觉得这个会影响到妙言原有的简洁，等哪天我想到了更好的方式来回复这个issue哦
