### ISSUE TITLE
tw，考虑一下中文排版的段首自动空两格呗

### ISSUE THREAD

**Issue by youbaowangsheng** [tw93/MiaoYan#110]

**Comment by tw93** [comment]
有没有类似场景 辛苦截图看看哦

**Comment by tw93** [comment]
这个貌似是doc那种做法，markdown 讲道理应该很少有自动空两格的场景，先关闭，有问题可以继续打开~

**Comment by youbaowangsheng** [comment]
英文中当然没有空两格的需求。
但用md中文写作第一行空两格，看起来确实好看多了。我看到有个自动排版的功能，但是具体发生了什么看不到。
如果在自动排版的过程中，对中文段落增加空格，我觉得是个有用的功能。
