### ISSUE TITLE
公式渲染问题

### ISSUE THREAD

**Issue by sunruisjtu2020** [tw93/MiaoYan#113]
对于LaTeX公式
```latex
$$\begin{cases} x&=1\\ y&=2\end{cases}$$
```
MWeb可以正常渲染为多行公式，而妙言渲染为单行公式。
![SCR-20220808-ujt](https://user-images.githubusercontent.com/42465638/183435976-14dd2ef4-2a24-4016-83cf-c76bed4e4b93.jpeg)
![SCR-20220808-uk5](https://user-images.githubusercontent.com/42465638/183436011-6d8514f8-097c-4b98-ac1c-7e30154f670e.jpeg)

**Comment by tw93** [comment]
谢谢反馈，这个属于功能增强，放在一个版本

**Comment by tw93** [comment]
@sunruisjtu2020 
看看这样能否满足使用
```
<div>$$\begin{cases} x&=1\\ y&=2\end{cases}$$</div>
```

**Comment by sunruisjtu2020** [comment]
@tw93 不错

**Comment by tw93** [comment]
这个问题先关闭，后面我会写一个妙言使用技巧的文档🤣
