### ISSUE TITLE
希望引入markmap这样编辑时就很有条理，希望增加

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [tw93/MiaoYan#115]
希望markdown可以直接生成markmap导图，麻烦开发者了

**Comment by tw93** [comment]
有案例和使用场景吗 辛苦列一下

**Comment by shoudeyunkaijianyueming** [comment]
可能对您不是很尊重，我想把妙言当成我obsidian的辅助编辑器，因为obsidian的缺点是很大很全，但obsidian的大纲很简陋，所以我想把妙言当成辅助编辑器，如果它有实时的大纲和思维导图，我在编辑时会感觉很有逻辑

**Comment by shoudeyunkaijianyueming** [comment]
最好是这种思维导图又是可编辑的，亦或者说幕布需要导入才能产生思维导图，而我希望妙言可以直接读取md文件，并支持在编辑时就有思维导图，可能我说的要求很苛刻，但是只是提个建议

**Comment by tw93** [comment]
已经完成 等待这次上线，可去推特看效果

**Comment by tw93** [comment]
已经支持辛苦更新最新版本
