### ISSUE TITLE
bug反馈，关于输入文本内容会跳行/闪屏的情况

### ISSUE THREAD

**Issue by thatshinji** [tw93/MiaoYan#117]
![bug](https://user-images.githubusercontent.com/91775458/184528588-7b63052d-0be3-4be2-84ee-686e8ff13a20.gif)
可以看一下录制的gif， 当md文本内容超过一屏后，再输入文字会频繁跳行的样子，版本是最新的 1.3.1

**Comment by tw93** [comment]
收到 谢谢反馈 这个问题属于部分机型bug 我自己电脑没有复现，最近待发布版本高优先级解决

**Comment by thatshinji** [comment]
> 收到 谢谢反馈 这个问题属于部分机型bug 我自己电脑没有复现，最近待发布版本高优先级解决

机型及操作系统相关信息：
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
macOS Monterey 12.4（21F79）

**Comment by fanpeizhou** [comment]
我也遇到了类似的问题，加了个TAB缩进后，那行就无法编辑，用退格键甚至会闪退

**Comment by tw93** [comment]
@fanpeizhou 是最新版本吗

**Comment by fanpeizhou** [comment]
> @fanpeizhou 是最新版本吗

是的

**Comment by tw93** [comment]
你的电脑也是13寸的吗

**Comment by fanpeizhou** [comment]
> 你的电脑也是13寸的吗

是的 2020款MacBook Air，13寸

**Comment by tw93** [comment]
> > 你的电脑也是13寸的吗
> 
> 
> 
> 是的 2020款MacBook Air，13寸

太感谢了 那我有突破点了

**Comment by tw93** [comment]
@fanpeizhou @thatshinji 
辛苦帮忙测试[这个包](https://cdn.fliggy.com/upic/MiaoYan 2022-08-17 19-49-24.zip)

**Comment by thatshinji** [comment]
> @fanpeizhou @thatshinji 辛苦帮忙测试[这个包](https://cdn.fliggy.com/upic/MiaoYan1.zip)

试了，还是不行，还是会跳到差不多首行的位置

**Comment by fanpeizhou** [comment]
> @fanpeizhou @thatshinji
> 辛苦帮忙测试[这个包](https://cdn.fliggy.com/upic/MiaoYan1.zip)

我测不了了，在旧版本上之前的bug复现不了了。莫名其妙又好了，奇怪

**Comment by tw93** [comment]
@thatshinji 推特私信沟通

**Comment by fanpeizhou** [comment]
> 最近找了几台朋友电脑测试，还是没有复现，太难了，这里我持续关注着，一旦我机器复现了就好修复了

好的，我发现了的话立马告知。辛苦了！

**Comment by Loner1024** [comment]
我也出现了这个情况
MacBook Pro（14英寸，2021年）
版本：1.4.6

**Comment by tw93** [comment]
@Loner1024 谢谢反馈 我再找找复现方法

**Comment by shell-Raining** [comment]
> @Loner1024 谢谢反馈 我再找找复现方法

我也遇到了这个问题，现在有一份可以复现的文件，想要推特发给你，但是无法私信

**Comment by Loner1024** [comment]
找到了一个在我电脑上复现的方法，调整窗口高度占满整个屏幕，出现闪屏问题，不占满的情况下没有这个问题

**Comment by tw93** [comment]
> 找到了一个在我电脑上复现的方法，调整窗口高度占满整个屏幕，出现闪屏问题，不占满的情况下没有这个问题

感谢 我今天试试

**Comment by tw93** [comment]
噗 疯狂测试还是不能复现😭

**Comment by thatshinji** [comment]
> 噗 疯狂测试还是不能复现😭

我用了1.4.7版本后暂时没有复现这问题了🤔

**Comment by tw93** [comment]
好勒 我先关掉，后面发现了，辛苦可以直接推特私信，这样效率更高
