### ISSUE TITLE
期待能有编辑预览模式分屏显示的功能

### ISSUE THREAD

**Issue by m1911star** [tw93/MiaoYan#119]
可将左侧的目录都收起，只保留编辑区和预览区的模式

**Comment by tw93** [comment]
最近在做一个即时渲染能力，类似 Typroa 效果，是否可以解决你这个问题？

**Comment by m1911star** [comment]
> 最近在做一个即时渲染能力，类似 Typroa 效果，是否可以解决你这个问题？

当然！赞！

**Comment by tw93** [comment]
这个问题属于需求类建议，非bug先关闭哦，等做完了上线了，会通过推特和版本更新日志，还有这条issue来通知大伙~

**Comment by m1911star** [comment]
虽然关闭了，还是补充一个建议，要不要加个label，这样便于分类 issue（我看现在的还是github默认的）

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/issues/391#issuecomment-3536452913
@m1911star @hezhizhen @JounQin  大伙去看看这个，支持了 分栏编辑模式
