### ISSUE TITLE
应用无法打开，报恶意应用

### ISSUE THREAD

**Issue by shellRaining** [tw93/MiaoYan#120]
电脑为 MacBook Air m1，系统为 Monterey 12.5，参考之前的 issue 无法解决，测试 1.3.1 版本和 1.2.0 版本，均无法打开，截图如下
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/72488394/185286607-cb93496f-a0d5-4e30-a1ed-47a1a98854f2.png">

**Comment by tw93** [comment]
辛苦试试官方github下的版本看看有问题吗

**Comment by conanjunn** [comment]
我也遇到了，为什么会这样？

**Comment by vampuke** [comment]
+1  intel版本   而且下载历史版本装上也打不开了

**Comment by shellRaining** [comment]
> 辛苦试试这个版本 [下载](https://cdn.fliggy.com/upic/MiaoYan4.zip)

谢谢，这个版本是可以使用的

**Comment by jievince** [comment]
> > 辛苦试试这个版本 [下载](https://cdn.fliggy.com/upic/MiaoYan4.zip)
> 
> 谢谢，这个版本是可以使用的

这个版本也没法用

**Comment by jievince** [comment]
![image](https://user-images.githubusercontent.com/38901892/185336753-a80254c5-ace3-4905-9c53-56c7b55b1b1d.png)

**Comment by shellRaining** [comment]
> ![image](https://user-images.githubusercontent.com/38901892/185336753-a80254c5-ace3-4905-9c53-56c7b55b1b1d.png)

你可以尝试升级一下 macOS 的版本，现在 Monterey12.5.1 已经有了，在关于本机中检查更新就可以

**Comment by jievince** [comment]
那提个建议, 最好release新版本的时候写下要求的系统版本号 💯

**Comment by tw93** [comment]
抱歉大家 今天应该是证书过期了，辛苦去下载最新版

**Comment by tw93** [comment]
请使用 1.4.6 版本，兼容性已测试ok
https://github.com/tw93/MiaoYan/releases/tag/V1.4.6
@jievince

**Comment by tw93** [comment]
@jievince 最后好了吗
