### ISSUE TITLE
更新最新版本后妙言无法打开

### ISSUE THREAD

**Issue by jievince** [tw93/MiaoYan#122]
![image](https://user-images.githubusercontent.com/38901892/185335868-f0e0af14-ab67-460f-a52c-b9ba282428b7.png)

**Comment by jievince** [comment]
mbp m1, mac ox 12.1

**Comment by tw93** [comment]
@jievince 辛苦去官网下最新版本

**Comment by tw93** [comment]
从官网github下最新包试试
