### ISSUE TITLE
虽然话不好听，但我始终不理解这重复造轮子的意义

### ISSUE THREAD

**Issue by abcmiao** [tw93/MiaoYan#123]
去看看joplin，看看obsidian，看看typora
为什么还要造一个没有啥新颖的markdown编辑器？
开源的joplin，你的东西他全有。而你只做了mac版，浪费人生啊，大兄弟，虽然话不中听。

如果你能兼顾他们的优势，做出一个更牛逼的，那当我放屁了

**Comment by abcmiao** [comment]
还是关注你，希望你能取长补短

**Comment by tw93** [comment]
谢谢反馈
总体回复
当你不抱功利心去做东西的时候你就不会这样觉得了
第一，这其实是我学swift的一个练手项目
第二，这是我周末无聊时候敲代码的一个乐趣
第三，做妙言不为了赚钱，也不缺钱，只是交个朋友

**Comment by tblx** [comment]
> 还是关注你，希望你能取长补短



> 去看看joplin，看看obsidian，看看typora 为什么还要造一个没有啥新颖的markdown编辑器？ 开源的joplin，你的东西他全有。而你只做了mac版，浪费人生啊，大兄弟，虽然话不中听。
> 
> 如果你能兼顾他们的优势，做出一个更牛逼的，那当我放屁了

练手项目做成这样挺不错的，而且开源免费界面好看，还在持续迭代。再说什么事情都是从小做起来的
