### ISSUE TITLE
Incorrect tag released

### ISSUE THREAD

**Issue by JounQin** [tw93/MiaoYan#124]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/8336744/185401850-6e84d41e-9350-4902-8ec7-84fe4015699a.png">

<img width="244" alt="image" src="https://user-images.githubusercontent.com/8336744/185401969-7c781d7b-2032-4d02-8ee5-ceadc72a83eb.png">

不太懂这个版本号😂

**Comment by tw93** [comment]
啊啊啊啊，谢谢反馈，已经修复，我大意了
