### ISSUE TITLE
V1.4.3 Cannot Open 

### ISSUE THREAD

**Issue by englipan** [tw93/MiaoYan#125]
早上打开妙言收到更新推送, 点击更新进度条走完, 显示安装错误, 由于回滚后依旧无法打开现在截图无法提供. 
随后尝试进入妙言官网手动下载: 

OS: macOS  Monterey V12.4   
Miaoyan DownloadLink:  https://github.com/tw93/MiaoYan/releases/download/V1.4.3/MiaoYan.dmg

V1.4.3 安装后打开显示如下: 
![image](https://user-images.githubusercontent.com/8935579/185417368-57720e0d-f62e-4639-a4c7-cc0fc9969ead.png)

尝试回滚至 [V1.3.1 Hurry up](https://github.com/tw93/MiaoYan/releases/tag/V1.3.1), 无法打开应用, 显示同样如下, 无任何安全提示问题: 
![image](https://user-images.githubusercontent.com/8935579/185418669-1ac4e06c-2786-44be-ac60-8589cb191083.png)

期望能够得到解决, 感谢.

**Comment by tw93** [comment]
很抱歉，今天早上证书过期了，当前1.4.3使用的新证书，当前1.4.3是没有问题的
辛苦参考这个 https://zhuanlan.zhihu.com/p/52389383 文档试试

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/185423792-27117ee1-3edb-4020-afd2-6651b2a02aad.png)
这里按理会有一个允许打开任意app，你试试，假如还不行，辛苦推特私信沟通，效率高一些

**Comment by englipan** [comment]
用Tecent Lemon彻底删除妙言后, 重新下载最新 Release 后依次尝试了 
1. 修改权限 chmode +x   /Applications/MiaoYan.app/Contents/MacOS/MiaoYan
2. 打开任意来源, anywhere 开启.  
3. 进入Application 文件夹右键打开miaoyan.   

所有的结果都是无法打开妙言  "The Application can't be opened", 之前有很多软件遇到安全中心需要验证, 可以在苹果软件设置-安全-点击"仍然打开"可以打开, 这个是第一次遇到. 

以前一般会出现类似这种: 

![image](https://user-images.githubusercontent.com/8935579/185459262-c1bf4c03-aeb1-4c0f-bd88-f9bc2ae8dd85.png)
下文苹果安全中心文章中的这些和这次遇到的不一样:

https://support.apple.com/en-us/HT202491


不知道是不是苹果的啥抽风了, 等有空了再研究一下, 辛苦作者

**Comment by tw93** [comment]
辛苦试试这个
从绕过公证（扩展）这里开始尝试
https://macwk.com/article/macos-file-damage

**Comment by englipan** [comment]
尝试步骤如下:
方法一:  无效  
```
1. $ sudo xattr -rd com.apple.quarantine /Applications/MiaoYan.app   
无效: 
> app cannot opened. 

```

**Comment by englipan** [comment]
```

尝试方法 2, 使用以下方法后成功打开. 

```
2. 

$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

$ sudo codesign --force --deep --sign - /Applications/MiaoYan.app
/Applications/MiaoYan.app: replacing existing signature

```

**Comment by zhyncs** [comment]
I met the same issue and use `sudo codesign --force --deep --sign - /Applications/MiaoYan.app` to solve it.

**Comment by englipan** [comment]
> I met the same issue and use `sudo codesign --force --deep --sign - /Applications/MiaoYan.app` to solve it.

Haha, If I met this after you, it’d save my time. But anyway, thanks for open source, and thanks to the author for giving us so a fantastic app.

**Comment by jievince** [comment]
> sudo codesign --force --deep --sign - /Applications/MiaoYan.app

对我的没有用, 我是macos 12.5.1
![image](https://user-images.githubusercontent.com/38901892/185547010-44bad67d-f407-4e82-97a7-e6e63ea7b7c0.png)

**Comment by tw93** [comment]
@jievince 彻底卸载以后，安装最新1.4.3版本

**Comment by jievince** [comment]
彻底卸载了, 也安装的最新的, 都不行, 其他issue提到的解决方法都尝试了, 都不行.

**Comment by tw93** [comment]
@jievince 我先找一下解法，有效果告知你，由于这次证书过期（哎我想骂苹果），耽误你使用了，抱歉哈

**Comment by wlf92** [comment]
我也遇到一样的问题，跟着那个解锁文档全操作了还是不行。

**Comment by tw93** [comment]
终于修复了，辛苦 @wlf92 @jievince 使用1.4.4版本，同时防止文件重叠，请卸载老版本。
https://github.com/tw93/MiaoYan/releases/tag/V1.4.4

**Comment by wlf92** [comment]
大佬大佬，这个最新的貌似又不行了 Mac mini (2018) Version 12.4 (21F79)

**Comment by tw93** [comment]
@wlf92  请使用最新版本1.4.7，最近被mac beta的测试版本弄吐了，等到正式版本再发布新版本好啦
