### ISSUE TITLE
优化排版时会修改代码格式

### ISSUE THREAD

**Issue by Loner1024** [tw93/MiaoYan#127]
点击优化排版后，会修改代码块里的代码格式
版本：1.4.3

![Kapture 2022-08-19 at 22 12 39](https://user-images.githubusercontent.com/20189164/185638368-a22315c1-761a-4e34-83d8-bad22800132f.gif)

**Comment by tw93** [comment]
谢谢反馈，放下一个版本修复
你试试重新切换一下文章列表，试试是否可以恢复

**Comment by Loner1024** [comment]
> 谢谢反馈，放下一个版本修复 你试试重新切换一下文章列表，试试是否可以恢复

试了一下，并不会恢复

**Comment by tw93** [comment]
哈哈 那应该bug无疑了

**Comment by shell-Raining** [comment]
> 哈哈 那应该bug无疑了

还有一个问题，输入中文的同时使用英文标点（半角），然后格式化会导致光标从格式化前编辑的位置跳转到其他地方

**Comment by tw93** [comment]
已经修复，放到最近一个版本发布
还有一个很神奇的功能  **妙言swift居然支持Prettier格式化** 了，一起上线

**Comment by tw93** [comment]
1.5.0 版本已经发布，https://github.com/tw93/MiaoYan/releases/tag/V1.5.0
可以去更新
