### ISSUE TITLE
无法打开“妙言.app”，因为Apple无法检查其是否包含恶意软件。

### ISSUE THREAD

**Issue by LukeLiou** [tw93/MiaoYan#128]
![image](https://user-images.githubusercontent.com/43230973/185722737-ab8cdc46-ee2e-4d15-9ea8-d62672c28b1a.png)
macOs12.4，希望问题得到解决，祝好盼复

**Comment by LukeLiou** [comment]
已更改设置 已经解决🙏

**Comment by tw93** [comment]
谢谢反馈
一早我更新了一个兼容性更强的版本，可以试试
https://github.com/tw93/MiaoYan/releases/tag/V1.4.6
