### ISSUE TITLE
代码块中的一部分被错误渲染为文档间跳转

### ISSUE THREAD

**Issue by shell-Raining** [tw93/MiaoYan#129]
代码块如下
<img width="691" alt="image" src="https://user-images.githubusercontent.com/111564053/185967953-5811578f-19ec-4d5f-a055-7dba8a2043f8.png">
渲染如下
<img width="676" alt="image" src="https://user-images.githubusercontent.com/111564053/185968034-39fbce75-995b-4fbc-9d57-14a5192a2a7c.png">

我查了一下 markdown 的官方语法，没有找到这个用法，而文章间跳转和文章内跳转也可以使用链接（或者 html 语法）的方式来实现，所以想提出一点小建议，希望可以尽量和 markdown 官方语法贴近

**Comment by tw93** [comment]
相当于是指你这边本来是想着在代码中，特地显示成[[xxx]]，然后被转换成了链接形式哦？
这一块我这样优化如何，对于注释内的内部跳转链接不做转换，默认显示成[[x]]。
关于这个语法，其实算是当前主流打内联笔记本的一个约定成俗的写法，习惯这一块的写法的同学更愿意这样写，平时用你说的这种markdown也可以的

**Comment by shell-Raining** [comment]
> 相当于是指你这边本来是想着在代码中，特地显示成[[xxx]]，然后被转换成了链接形式哦？ 这一块我这样优化如何，对于注释内的内部跳转链接不做转换，默认显示成[[x]]。 关于这个语法，其实算是当前主流打内联笔记本的一个约定成俗的写法，习惯这一块的写法的同学更愿意这样写，平时用你说的这种markdown也可以的

是的，这样优化挺好的。我不太熟悉其他的笔记本，所以冒昧的提一下😀

**Comment by tw93** [comment]
嗯嗯 很感谢反馈，我最近版本解决，到时候issue通知到你

**Comment by shell-Raining** [comment]
可以和您在推特上私信吗，上次那个光标跳转的 issue 我也遇到了，还有一些关于格式化文档的问题

**Comment by shell-Raining** [comment]
这个是一份我感觉比较简单的文档，一旦从最底下按回车然后删除，就会复现光标跳转到最顶处的 bug，我感觉很有可能是第一个 bash
代码块中某些特殊字符导致这个 bug。而且还有一些小端倪，在 bash 代码块的下面的第一个一级标题处，编辑模式下颜色显示不太正常

Tw93 ***@***.***> 于2022年8月23日周二 20:46写道：

**Comment by tw93** [comment]
完全可以私信哈 怎么效率高怎么来

**Comment by shell-Raining** [comment]
> 完全可以私信哈 怎么效率高怎么来

推特显示无法私信

![image](https://user-images.githubusercontent.com/111564053/186183576-5dc05a77-3804-4866-9131-be63a3e18280.png)

**Comment by tw93** [comment]
啊 我的天 是不是需要关注

**Comment by shell-Raining** [comment]
> 啊 我的天 是不是需要关注
哦哦好了，我关注了，不过是在最左侧的私信中搜索的，所以显示无法私信，在个人页面是有私信按钮的

**Comment by tw93** [comment]
已修复，会放到最近一个版本发布~   预计下周的样子
