### ISSUE TITLE
[Bug] 侧边栏和文字编辑区域的暗黑模式没有同步更新

### ISSUE THREAD

**Issue by jievince** [tw93/MiaoYan#130]
![image](https://user-images.githubusercontent.com/38901892/186051405-8e37cd50-38f9-42b4-822a-a29c07002a19.png)
重新刷新下才行

**Comment by tw93** [comment]
很感谢反馈！
😂辛苦说一下复现步骤，最好可以录制一个mp4的方式，感谢感谢
因为我这边不能复现你这个问题

**Comment by tw93** [comment]
已经修复，会放到最近一个版本发布，预计下周的样子

**Comment by tw93** [comment]
1.5.0 版本已经发布，https://github.com/tw93/MiaoYan/releases/tag/V1.5.0
可以去更新
