### ISSUE TITLE
MacOS Monterey 12.5 闪退无法解决

### ISSUE THREAD

**Issue by MingChen2020** [tw93/MiaoYan#131]
如题，mac系统运行闪退严重，而且新建文件无法编辑和保存，莫名其妙消失。

Miaoyan UI漂亮，设计合理，非常适合写作！但是以上问题一直没解决。希望能解决！感谢开发者！

**Comment by tw93** [comment]
请问一下是1.4.6版本吗？方便给到一些辅助定位信息吗？
需要一个录屏吗？我看看效果，对于闪退问题会第一时间解决

**Comment by MingChen2020** [comment]
Hi~ 感谢！我把崩溃日志发送到你主页邮箱[tw93@qq.com](mailto:tw93@qq.com)可以吗！现在可以了，闪退情况好像没有了。

**Comment by MingChen2020** [comment]
谢谢！

**Comment by tw93** [comment]
最近还有出现吗？
假如没有出现，我这边先关掉这个，因为这段时间我也没有复现

**Comment by MingChen2020** [comment]
目前还没有 感觉很不错的编辑器 谢谢开发者！
