### ISSUE TITLE
当某个目录的文档数量够多时，侧边栏出现下拉框时，隐藏第二个侧边栏，根本隐藏不掉，还可以拖拽

### ISSUE THREAD

**Issue by ChaoMing1** [tw93/MiaoYan#132]
🙊辛苦提 bug 前，去找一下 [历史的](https://github.com/tw93/MiaoYan/issues?q=) 是否有提，同时检查一是否为最新版本。辛苦提供版本号、录屏或者截图、复现路径，期待解决的点这几个说明帮助我更好的解决问题。提交前请删除这些文字。<br>
🙊Look for [issue](https://github.com/tw93/MiaoYan/issues?q=) before you mention bugs Whether it is mentioned, and check whether it is the latest version. Need to provide the version number, screen capture or screenshot, reproduction path, and look forward to the points to be solved. These instructions help me better solve the problem. Please delete these words before submitting.

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/38456117/186828791-c5679cec-349d-4c4e-93ba-28e188f73ba5.png">

**Comment by ChaoMing1** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/38456117/186829417-860fc5df-f44b-4a97-be98-58ef043b7683.png">
最新版本号

**Comment by tw93** [comment]
习惯试试快捷键  command + 1、2、3、4  你会发现很方便

**Comment by ChaoMing1** [comment]
![2022-08-26_18-03-36 (1)](https://user-images.githubusercontent.com/38456117/186880585-b7c53a5e-a8da-4bb8-bab3-1047258679da.gif)

看上图，就是用的快捷键，反馈的问题是侧边栏没有完全隐藏

**Comment by tw93** [comment]
哦哦 好勒 我复现复现看

**Comment by tw93** [comment]
找到原因了，应该是你的设置有问题，修改这里即可
![image](https://user-images.githubusercontent.com/8736212/187065977-9f0ced58-97a9-40ef-a186-914a776938a4.png)

**Comment by ChaoMing1** [comment]
的确是的，这个问题太弱智了，haha~

**Comment by tw93** [comment]
哈哈哈 没事没事 我查了一会儿 最后发现是这个 大吃一惊 哈哈
