### ISSUE TITLE
会考虑加入 vim-mode 吗？

### ISSUE THREAD

**Issue by immotal** [tw93/MiaoYan#135]
我试用了妙言，感觉特别棒，如果是用来替代 Ulysses 来进行日记或者小说的写作，我觉得很赞。
但是我平时用的最多的是写技术文档， vim-mode 更加灵活。目前在用的 Quiver 也是因为其实市面上为数不多的支持 vim-mode 的编辑器，作者有考虑过加入这份 feature 吗？谢谢

**Comment by tw93** [comment]
请教一下 Quiver 如何支持 vim-mode，我去试试看

**Comment by immotal** [comment]
<img width="568" alt="截屏2022-08-31 下午7 51 59" src="https://user-images.githubusercontent.com/40708234/187672219-681c1cf2-5cd4-4de6-b08b-9275b119eaef.png">
这个是 Quiver  vim-mode 的设置，具体的使用如下：
<img width="558" alt="截屏2022-08-31 下午7 53 36" src="https://user-images.githubusercontent.com/40708234/187672495-bfe1212a-f690-4503-8d96-e2a788dfe61f.png">
可以看到光标是 vim 模式的那种

**Comment by tw93** [comment]
这个需求我理解很小众，辛苦看看有没有一些mac 的插件支持使用
https://github.com/dbalatero/VimMode.spoon
https://github.com/FelixKratz/SketchyVim
https://github.com/dwarvesf/VimMotionApp
