### ISSUE TITLE
是否有计划支持Windows？

### ISSUE THREAD

**Issue by yansheng836** [tw93/MiaoYan#136]
看起来这是个很炫酷的markdown编辑器，但是当前只支持mac，想请教下是否有计划支持Windows？

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/issues/134
需要等到妙言 iPhone 版本ok后，可能才会考虑～

**Comment by yansheng836** [comment]
额，不好意思居然提了重复的问题，这搜索好像有点问题啊……

![image](https://user-images.githubusercontent.com/45334066/187370839-98f5a1fa-6965-4030-b7f4-72f87a0a5a90.png)
