### ISSUE TITLE
文件名里有`/`时会误报: 文件名已存在

### ISSUE THREAD

**Issue by jievince** [tw93/MiaoYan#137]
![image](https://user-images.githubusercontent.com/38901892/187335245-6a403448-f575-4910-bfc9-87f937f000f4.png)

**Comment by tw93** [comment]
感谢反馈，这里的确会有这个问题，因为这个标题也是你对应markdown源文件的文件名，我看看怎么解决能够避免

**Comment by jievince** [comment]
是不是可以改标题的时候重命名下对应的文件名

**Comment by tw93** [comment]
hack了下 已经修复 放最近一个版本发布

**Comment by tw93** [comment]
1.5.0 版本已经发布，https://github.com/tw93/MiaoYan/releases/tag/V1.5.0
可以去更新
