### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by baimasi** [tw93/MiaoYan#14]
是不是可以添加图片粘贴的功能

**Comment by tw93** [comment]
已经支持，可以在检查更新中更新到0.4.0版本

**Comment by baimasi** [comment]
测试了一下 发现个问题，两个不同的文档图片存放是在一个文件夹下的，这样很不利于文档导出和分享
<img width="620" alt="image" src="https://user-images.githubusercontent.com/28396944/173796529-525d16cc-8313-4106-8513-bb9441b29a9a.png">
是否有机会优化一下,以文档的为根目录将资源目录分开
