### ISSUE TITLE
PPT场景下加入思维导图功能？

### ISSUE THREAD

**Issue by hoochanlon** [tw93/MiaoYan#143]

**Comment by tw93** [comment]
当前已经支持，试试这个代码，复制这个文件去妙言看看
https://miaoyan.app/Release/demo/MiaoYan%20Markmap.md

这样的格式
```
```markmap
- 妙言
  - 好不好看
    - 好看
    - 好用
  - 好不好玩
    - 好玩
    - 漂亮
  - 还可以这样
    - 试试链接
    - [Github](https://github.com/tw93/MiaoYan/releases/tag/V1.4.3)
```
```

**Comment by hoochanlon** [comment]
ppt显示不了思维导图啊

**Comment by tw93** [comment]
那应该就是我没有兼容到PPT模式，下一个版本兼容一下，我重新打开一下

**Comment by tw93** [comment]
已支持，最近一个版本发布，到时候通知你~

PPT中支持markmap，此外markmap支持单独自定义高度入，`  --markmap-height=500`，

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/releases
已支持，在1.6 版本已发布

**Comment by hoochanlon** [comment]
思维导图可以图像编辑就好了，看代码挺乱的；这样做的好处，个人对软件粘连性强一些。这仅是我个人意见了。
