### ISSUE TITLE
不能用触控板左右滑动页面，只能鼠标点，容易触发系统备忘录

### ISSUE THREAD

**Issue by hoochanlon** [tw93/MiaoYan#145]
上下左右的方向键，不如触控板来的顺畅。另外翻页箭头调上面一点，太容易打开快速备忘录了

<img width="1440" alt="截屏2022-09-13 11 28 50" src="https://user-images.githubusercontent.com/35732922/189801233-5e95dc9a-9b9b-4162-bb57-b3452bede341.png">

**Comment by tw93** [comment]
试试空格键下一页
触控板和翻页位置说得有道理，我这个版本加一下

**Comment by tw93** [comment]
已经支持箭头调上调左一些
关于触摸屏滑动我看了看，实现效果不是很好，先不弄了（参考keynote也没有支持，有可能会误触的原因）
预计周末前发布

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/releases
箭头调上调，在1.6 版本已发布，可取试试
