### ISSUE TITLE
是否考虑支持子文件夹或文档标签？

### ISSUE THREAD

**Issue by KrabsWong** [tw93/MiaoYan#146]
### 背景

目前是通过文件夹来对文章做归类和管理，对我个人来说，内容分类的粒度上稍显不够，我的场景如下

1. 会创建一个目录来放工作相关的内容
2. 工作内容中会涉及到 **技术方案设计**， **项目管理**，**撰写使用文档** 等
3. 以上内容目前只能杂糅在一个文件目录下（当然也可以拆分成多个目录，但是缺少了一些从属关系）

### 诉求

基于以上背景，希望能支持

> 以下两点，**之于我而言**，任何一个特性均可将目前的文档管理粒度达到一个灵活处理的程度

1. 子文件夹，以便对内容做更细粒度的管理
2. 文档打标签：可以通过标签对内容做筛选（相对一目了然一些）

## 以吹结尾

用起来舒适的很，配色舒适的很，logo 酷的很，潮流周刊好的很。

**Comment by tw93** [comment]
很感谢反馈，这一块我想想怎么实现，即符合使用要求，又不那么突兀，最开始时候有尝试过多级文件，自我感觉不是很好看，我下一个版本的时候试试，及时交流~

**Comment by KrabsWong** [comment]
> 很感谢反馈，这一块我想想怎么实现，即符合使用要求，又不那么突兀，最开始时候有尝试过多级文件，自我感觉不是很好看，我下一个版本的时候试试，及时交流~

多级文件夹的展示方式，我也觉得不好看（有点儿太重了）
Github issue 管理中的标签，似乎也是个不错的轻量分类的方案。

期待下。

**Comment by tw93** [comment]
我试试标签的概念

**Comment by tiandankanfeng** [comment]
是的，管理子文件夹感觉还是蛮实用的

**Comment by chunyang-wen** [comment]
请问这个 issue 有更新吗？

**Comment by yuyuko233** [comment]
现在如何了? 有更新吗?
