### ISSUE TITLE
希望出windows版

### ISSUE THREAD

**Issue by ethan-phu** [tw93/MiaoYan#148]
🏂 很感谢你给妙言提建议，辛苦将你的需求描述清楚一些，特别期待你可以说明白这个功能很有用，没有加这个功能会让你很遗憾。提交前请删除这段文字。<br>
🏂 Thank you for your advice to MiaoYan. Need you describe your needs clearly. I especially hope you can make it clear that you will regret not adding this ability. Please delete this text before submitting.

**Comment by tw93** [comment]
谢谢帮忙答疑
