### ISSUE TITLE
mermaid ER图无法渲染

### ISSUE THREAD

**Issue by bluetoothvirus** [tw93/MiaoYan#149]
- 软件版本：1.5.0
![image](https://user-images.githubusercontent.com/77611237/190570213-d3c24a7e-1c0f-4647-9f2e-7d8fe6845bf5.png)
- 系统版本：macOS Monterey 12.6 21G115
- 硬件版本：MacBookPro16,2 (13-inch, 2020, Four Thunderbolt 3 ports, Quad-Core Intel Core i7 @ 2.3GHz)
- 更新检查结果：没有更新的版本 
![image](https://user-images.githubusercontent.com/77611237/190570272-ef88d669-2f30-4c5c-8588-47c4909b7f65.png)

- 操作过程：新建一页笔记并输入以下附件中内容
[20220916_miaoyan_mermaid_bug.md](https://github.com/tw93/MiaoYan/files/9581209/20220916_miaoyan_mermaid_bug.md)，输入结果如下图：
![image](https://user-images.githubusercontent.com/77611237/190570354-bbaa5472-f49a-4d6f-9f1b-d68366556286.png)

- 结果：流程图相关代码正常渲染，但erDiagram相关代码块渲染出了一个空的结果：
![image](https://user-images.githubusercontent.com/77611237/190569878-13f1c598-cded-4c08-b038-c76a6f1ff994.png)
- 期望：erDiagram正常渲染，得出结果与[mermaid文档关于ER Diagram的相关介绍](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram)一致：
![image](https://user-images.githubusercontent.com/77611237/190570449-1f4d2ccc-71bc-4bb1-a817-8bced5d7d864.png)

**Comment by tw93** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/8736212/190632935-f89cae9a-0575-4388-aff4-c9642903fe5f.png">
辛苦等最新版本发布，预计这两天，已经OK，更新到了最新版本，应该都支持了

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/releases
已修复，在1.6 版本已发布
