### ISSUE TITLE
快捷键自动格式化文档后，卡死无响应

### ISSUE THREAD

**Issue by wangwei10061** [tw93/MiaoYan#150]
感谢作者，就想要这么yi一款轻量级的markdown笔记软件，初次尝试，遇到一点小问题

快捷键自动格式化文档后，卡死无响应

![image](https://user-images.githubusercontent.com/9947149/190669427-a6d26b6a-3307-40fb-824d-89415a0a5df1.png)

**Comment by tw93** [comment]
看起来你这边mac的版本有些太太太老了，辛苦升级到11以上，体验会好太多。
现在你这个截图相当于bug版本了
