### ISSUE TITLE
支持嵌套目录结构

### ISSUE THREAD

**Issue by chunyang-wen** [tw93/MiaoYan#156]
我想确认下，是否支持嵌套的层级目录。现在目录结构只有一级。比方说我想按照如下方式去管理：

+ work
  + 2022
    + Sep

现在我只能新建一层目录，然后通过文件名的方式来管理。其实也可以。但是我想如果能支持目录结构可能会更清晰点。

**Comment by tw93** [comment]
后续会通过标签的方式来实现文档的分类管理，暂时不会考虑多级目录，可见此issue
https://github.com/tw93/MiaoYan/issues/146

**Comment by chunyang-wen** [comment]
好的，这个 issue 先关闭。
