### ISSUE TITLE
截图软件的图片可以直接粘贴

### ISSUE THREAD

**Issue by chunyang-wen** [tw93/MiaoYan#159]
#81 中有人咨询是否可以复制图片粘贴。我试了下帖子中的功能，看样子是需要复制一个文件，然后粘贴。这种操作是可以的。

不清楚是否支持这种形式：例如我用某种截图或者截屏软件，然后就会复制到系统粘贴板，然后直接粘贴。

我是用的是 1.6.0 Miaoyan 版本

**Comment by tw93** [comment]
按理这个功能之前是支持的，1.6版本我关闭的拖拽文本的功能，应该是那个属性影响了，下一个版本我优化一下即可

**Comment by zhyncs** [comment]
> #81 中有人咨询是否可以复制图片粘贴。我试了下帖子中的功能，看样子是需要复制一个文件，然后粘贴。这种操作是可以的。
> 
> 不清楚是否支持这种形式：例如我用某种截图或者截屏软件，然后就会复制到系统粘贴板，然后直接粘贴。
> 
> 我是用的是 1.6.0 Miaoyan 版本

1.6.0 之前的版本是可以直接粘贴剪切板上的图片的，等作者更新优化吧

**Comment by tw93** [comment]
抱歉 已经优化了，一个选项的锅，等最近一个版本发布

**Comment by chunyang-wen** [comment]
> 抱歉 已经优化了，一个选项的锅，等最近一个版本发布

请问 release 的周期是？

**Comment by zhyncs** [comment]
非盈利产品，为爱发电，如果你能修复你可以提 pr，日常大家都有工作的，无法保证一个具体的周期吧，又不是公司发版> > 抱歉 已经优化了，一个选项的锅，等最近一个版本发布
> 
> 
> 
> 请问 release 的周期是？

**Comment by chunyang-wen** [comment]
> 

理解的，我不是催。我是尝试问问你有没有计划。要是要比较久，我就按照你建议的，先用之前的版本。谢谢啦。

**Comment by tw93** [comment]
哈哈  试试这个，一早打了一个包 @zhyncs  @chunyang-wen 
[妙言.app.zip](https://github.com/tw93/MiaoYan/files/9603428/app.zip)
为了避免频繁发布影响用户，尽量2周左右发一个

**Comment by tw93** [comment]
发布1.6.2版本，较 1.6.0 版本，修复 copy 图片到编辑器、按标题排序问题、窗口文字间距舒服调整、支持 shift+回车 不自动补充序号的模式
可以点击右上角妙言菜单栏检查更新，升级到 1.6.2
