### ISSUE TITLE
偏好设置-语言选项bug

### ISSUE THREAD

**Issue by koinzhang** [tw93/MiaoYan#16]
在偏好设置-语言选项，打开语言下拉菜单，点击已选中项目仍然会重启应用。比如当前语言是Chinese，下拉菜单再点击Chinese，会重启应用。
另外一个小建议，偏好设置-语言下拉菜单的"Chinese(Simplified)"改为“中文（简体中文）"

**Comment by tw93** [comment]
1. 下一个版本修复了，预计周末发布，谢谢反馈哦，这样体验不错
2. Chinese(Simplified)这个其实是我故意设计的，因为比如老外，默认进来是中文，他其实是看不懂中文（简体中文）的，但是Chinese(Simplified)他就可以大概猜出来这里是设置语言的
