### ISSUE TITLE
有没有加入anki模式的打算？

### ISSUE THREAD

**Issue by hoochanlon** [tw93/MiaoYan#162]
anki整理碎片挺好的

**Comment by tw93** [comment]
抱歉 我对这个不是特别熟悉，你能够大概解释解释是一个啥不，或者业界有没有类似的产品我去玩玩

**Comment by hoochanlon** [comment]
差不多是这样子，和小卡片差不多

https://apps.ankiweb.net

https://apps.apple.com/cn/app/anki-note-%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E6%8A%BD%E8%AE%A4%E5%8D%A1%E7%9A%84%E5%A4%87%E5%BF%98%E5%BD%95/id1586139777

**Comment by tw93** [comment]
了解啦
抱歉 这个功能有些小众不太通用 放到妙言不太好实现 你可以试试其他方式
