### ISSUE TITLE
关于复制粘贴的问题

### ISSUE THREAD

**Issue by chunyang-wen** [tw93/MiaoYan#165]
我想咨询一个奇怪的问题。在妙言的编辑区我复制所有内容，然后去粘贴
+ Vim 中粘贴
+ 另外一个网页 Editor 中粘贴（类似于语雀网页版）

在 Vim 中看到的确是 Markdown 的内容；但是在网页中粘贴时，它没有识别是 Markdown 的内容，而是粘贴了在妙言中看到的内容（例如语法高亮，标题颜色等等）。但是我如果从 Vim 中把刚才的内容在复制出来，然后再重新粘贴到网页 Editor 中，它就可以正确的识别是 Markdown，然后去渲染。

所以我的问题是：从妙言中复制出来的东西和粘贴到 Vim 后再复制出来，这两个是不是有一些区别？

我也用了熊掌笔记，它是可以实时渲染到，从那个里面粘贴出来的东西，然后再复制到网页 Editor 中，也是正常的。

所以我不清楚从妙言的编辑区复制出来的东西是不是有什么特殊的？导致网页 Editor 没有办法正常去识别是个 Markdown，而是和妙言看到的一样的东西

从妙言中复制出来，然后粘贴到网页编辑器
<img width="327" alt="image" src="https://user-images.githubusercontent.com/2911134/191882298-bd28ea81-9aa1-4919-9767-31e3257d94db.png">

从 Vim 中复制出来粘贴到编辑器
<img width="466" alt="image" src="https://user-images.githubusercontent.com/2911134/191882346-a04a2ead-ad66-4ab7-8ad3-ddaa5aa362ea.png">

**Comment by tw93** [comment]
你说的这两个都是正常逻辑，我试了试妙言，也是你这边类似vim的效果，你这个网页版本的编辑器其实和word的效果是一样的，语雀你试试也是正常的效果，然后你试试word，就会有语法高亮了
这个效果其实和你从vscode copy的效果应该是一样的，也可以试试

**Comment by chunyang-wen** [comment]
我的需求是这样的：通常我用妙言来编辑东西。但是我要分享给别人的时候，就复制到那个网页编辑器。我希望它能够自动识别出 Markdown，然后用它自己的引擎来渲染。而不是粘贴成图片一的情况。我希望的时候和从 vim 中复制出来，然后去粘贴的效果。

**Comment by chunyang-wen** [comment]
刚又去试了下 vscode，里面复制出来再粘贴也不行。但是不知道为啥熊掌记(Bear)的就行。Bear 复制是复制 markdown 出来，我估计它有做一些细节的处理。

**Comment by tw93** [comment]
网页编辑器是啥？

**Comment by chunyang-wen** [comment]
Shift+Option+Cmd+V

可以配置覆盖掉它
https://www.cnblogs.com/leezx/p/11203484.html
