### ISSUE TITLE
申请一下在代码在编辑时候也有底色

### ISSUE THREAD

**Issue by wlf92** [tw93/MiaoYan#166]
![image](https://user-images.githubusercontent.com/7065616/191916492-0988917f-7146-4f4c-9e80-e115a3acee72.png)
现在编辑状态如上所示
可否新增一个优化，在代码(``` xxx ```)编辑状态也和预览状态一样增加底色
![image](https://user-images.githubusercontent.com/7065616/191916666-36f55f86-950e-4fdf-971f-3ced30ab6e10.png)

**Comment by tw93** [comment]
这一块主要考虑是？
我当时故意不加底色，但是想着更像编辑器的体验一些

**Comment by tw93** [comment]
好的 谢谢反馈 我空的时候去看看obs

**Comment by tw93** [comment]
均已支持，放到最近一个版本发布，先关闭这个issue，可以关注下一个版本。

https://user-images.githubusercontent.com/8736212/192128362-96f42e17-d127-4b14-9aeb-521c005c5219.mp4

**Comment by wlf92** [comment]
真棒，感激不尽。

**Comment by tw93** [comment]
[妙言.app.zip](https://github.com/tw93/MiaoYan/files/9640873/app.zip)

体验版本，欢迎试用以及帮忙测试看看～

**Comment by wlf92** [comment]
我试了下，toggle todo 没问题了，但是代码底色还是没有。
![image](https://user-images.githubusercontent.com/7065616/192180783-154a754a-1200-4acb-8bda-367faa985cb0.png)

**Comment by wlf92** [comment]
完美，谢谢老板。
