### ISSUE TITLE
预览模式下添加Front Matter支持

### ISSUE THREAD

**Issue by jw-12138** [tw93/MiaoYan#167]
非常喜欢妙言极简的设计，后面打算一直使用妙言作为主要的 markdown 编辑器。  

Front Matter 在博客写作中扮演的角色还是蛮重要的，可惜妙言在预览模式中没有对其作出处理。  
目前 Front Matter 在妙言的预览下是这样的：  

<img width="632" alt="image" src="https://user-images.githubusercontent.com/29943110/192687832-d8ad66d4-db39-4577-a49c-9a34616bf43b.png">

源码：

```markdown
---
title: 关于Web Audio中Analyzer输出的频率数据分布问题
date: 2022-08-19 12:45:37
desc: 随着iOS 16 beta 5的更新，细心的小伙伴可能注意到了……
tags:
  - WebAudio API
---
```

<br>
<br>

Front Matter 本质上可以理解为一段 YAML 配置，目前我能想到的能提升用户体验的方案有两个：  

1. 解析 Front Matter 到预览，可以像 GitHub 一样用表格展示出来，当然也可以是其他任何有条理的展示模式
  <img width="1029" alt="image" src="https://user-images.githubusercontent.com/29943110/192689247-64ed48cf-ef7f-4317-9345-e6364d902415.png">

2. 完全忽略 Front Matter，眼不见为净🤣

<br><br>

**Comment by tw93** [comment]
优化了下，判断下来假如有如下场景自动隐藏掉，会放到国庆前发布～

```
---
title: xxx
---
```

**Comment by jw-12138** [comment]
测试看下来没问题！感谢作者大大光速回复！👍
