### ISSUE TITLE
1.6.4 在 macOS 12.6 上频繁 crash

### ISSUE THREAD

**Issue by wlmzfx** [tw93/MiaoYan#168]
版本： 1.6.4
macOS： 12.6
附件中是crash log
[logs.zip](https://github.com/tw93/MiaoYan/files/9663150/logs.zip)

**Comment by tw93** [comment]
方便给一个大概的复现路径不

**Comment by wlmzfx** [comment]
> 

我再观察一下看怎么复现

**Comment by wlmzfx** [comment]
印象里应该是这样的操作步骤：
1. 安装，保留默认配置，使用iCloud存储
2. File -> Import -> 选择一个已经存在的 md 文件进行打开 （打开以后就crash了第一次）
3. 删除刚打开的md文件
4. 创建一个新的文件夹，File -> Single Open -> 选择一个md文件 （这里又crash了一次）

然后从Preferences里面把存储为改成本地文件夹，没有发现有crash的问题。

**Comment by tw93** [comment]
辛苦重新试试这个新包
https://fl-file.oss-cn-hangzhou.aliyuncs.com/upic/iNKDsE.zip

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/issues/169
归拢到这里一起讨论
