### ISSUE TITLE
代码块bug

### ISSUE THREAD

**Issue by Ham12** [tw93/MiaoYan#170]
当有多个代码块，且代码块内容较多时，输入"`"会特别卡，甚至在复制"```"时会导致软件崩溃

**Comment by tw93** [comment]
右上角点击检查更新，请升级1.7.1最新版本试试

**Comment by Q1ngShan** [comment]
过多代码块时，感觉是渲染问题，速度变得卡顿，可见下面测试录屏


https://user-images.githubusercontent.com/24487351/194741921-ba17d9cf-fb14-4f40-87d2-6642441eb730.mp4

**Comment by tw93** [comment]
方便将这个源文件也一并给过来吗 我本地测试一下

**Comment by Q1ngShan** [comment]
[测试.md](https://github.com/tw93/MiaoYan/files/9743149/default.md)
