### ISSUE TITLE
关于字符超长换行的建议。有个显示问题不知道算不算bug.

### ISSUE THREAD

**Issue by wlf92** [tw93/MiaoYan#171]
有个问题，不知道算不算bug，如果大佬有时间，可以优化看看。
当编辑模式字符超长。
![image](https://user-images.githubusercontent.com/7065616/193223145-029441ef-9c81-48b3-b5eb-26d1190ec1f5.png)
在预览模式展示结果会这样
![image](https://user-images.githubusercontent.com/7065616/193223239-dbf118fa-b954-4378-a0fe-b552830bbd04.png)
这莫名其名的换行和空格应该算是bug?
---
此外，能否提供一个开关？在 换行/不换行 进行切换，编辑和预览模式都统一 换行或不换行。

**Comment by tw93** [comment]
今天发一个版本 之前有推友建议过
预览的代码改成了换行

**Comment by wlf92** [comment]
大佬很热爱编程嘛，嘿嘿，节日快乐，加油。

**Comment by tw93** [comment]
哈哈哈 当作快乐的事情

**Comment by tw93** [comment]
右上角点击检查更新，请升级1.7.1即可

**Comment by wlf92** [comment]
额，感觉没有差别诶。。。

**Comment by tw93** [comment]
你把md文件给我下，我本地测试一下，你这个是代码区块吗？

**Comment by wlf92** [comment]
[temp.md](https://github.com/tw93/MiaoYan/files/9689500/temp.md)

是的

**Comment by tw93** [comment]
谢谢 空闲时间我试试 跟着下一个版本走
