### ISSUE TITLE
【Bug report】使用Tab导致编辑器格式就会混乱

### ISSUE THREAD

**Issue by schrodingercatss** [tw93/MiaoYan#172]
Version: V 1.7.1
Device: Macbook Pro 14 M1 pro
OS: MacOS Monterey 12.6

复现路径：
1. 在编辑器中多次按 Tab，光标就会移到行首，删除这些 Tab的光标位置不对，而且如果不删除接下来的行会继承上一行的 Tab
2. 在行末按 Tab，他会将整行往后移动，而不是当前位置之后的字符往后移动

**Comment by tw93** [comment]
谢谢反馈，下一个版本我修复一下

**Comment by dongjiahong** [comment]
我也碰到了这个tab的bug

**Comment by tw93** [comment]
哈哈 修复中哦 之前一段时间忙其他的去了

**Comment by tw93** [comment]
已经修复，着急可以试试这个包 https://static.tw93.fun/img/202211112245MiaoYan_beta.zip
