### ISSUE TITLE
【功能建议】增加模版功能

### ISSUE THREAD

**Issue by soapffz** [tw93/MiaoYan#175]
给写好的markdown右键添加设置为模版的功能

菜单【文件】中增加新建，二级菜单中显示模版

可以方便用来写一些日报周报之类的

～一点不完善的建议没有想得太清楚～

**Comment by tw93** [comment]
很好的建议，我空闲时候想想怎么弄哈，不过这一块比较特殊，每一个人的模版其实是不一样的，当前妙言其实支持复制生成副本，你可以试试在文档上 command + d 看看是否满足需求

**Comment by tw93** [comment]
模版功能我试了试还是没有想得太通用，先关闭这个issue，有好想法欢迎提
