### ISSUE TITLE
能否支持自动从quiver导入，方便旧文件迁移

### ISSUE THREAD

**Issue by jdz321** [tw93/MiaoYan#179]

**Comment by tw93** [comment]
支持的，唯一需要注意的就是 你导出的时候，记得选择quiver的排序方式为 日期创建 升序，这样导出后，在妙言里面，你的排序才是符合正常的（相当于升序导出，实际是降序的日期，这样回去就刚刚好），试试看是否OK

https://user-images.githubusercontent.com/8736212/197441853-09ffd94e-ec29-4d01-9f9e-3517c0473645.mp4

**Comment by jdz321** [comment]
我意思能不能自动从他存的地方导进来，不用手动导出，比如Mac是在`~/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary`，里面是json格式存储的数据

**Comment by tw93** [comment]
这就比较难了，或是说我比较懒了🙊
