### ISSUE TITLE
本地图片不能正常加载

### ISSUE THREAD

**Issue by lebang** [tw93/MiaoYan#18]
原 Typora 的文档目录，直接打开，预览图片都没法正常显示

**Comment by tw93** [comment]
截图一下源码模式的markdown格式，然后点击看一下图片是否存在原有的文件夹

**Comment by lebang** [comment]
图片存在，以绝对路径引入的，预览无法正常显示

**Comment by tw93** [comment]
@lebang 找到解决办法了，妙言由于沙箱安全，我不会让他读其他文件夹文件，也是为了保护大家隐私
可以先在文档当前文件夹下面建立一个img的文件夹，可以选择 Typora - 格式 - 图像 - 复制所有图像到...，选择这个文件夹即可
操作可见这个视频

https://user-images.githubusercontent.com/8736212/174416783-ba6deb21-1127-4b3c-877b-7baa52b08690.mp4
