### ISSUE TITLE
仓库的 README 的 gif 图加载比较慢

### ISSUE THREAD

**Issue by yiliang114** [tw93/MiaoYan#180]
可以在无痕模式下看到，没有加载出来时有一个奇怪的类似胶囊的块，不过gif加载完成之后后面走缓存几乎没有感觉了。 这里换个国内的图床会不会好点？

![1](https://user-images.githubusercontent.com/11473889/197555540-a1b23e30-4d40-4890-8e04-18fcf209073f.gif)

![image](https://user-images.githubusercontent.com/11473889/197555461-ea1dcd60-c0d5-413e-875b-64681d2bbf5e.png)

**Comment by tw93** [comment]
这个是github覆盖行为 其实是好的图床

**Comment by yiliang114** [comment]
> 这个是github覆盖行为 其实是好的图床

Soga 那就是估计因个人的网络而定的了
