### ISSUE TITLE
Open a specific folder in my Mac? 

### ISSUE THREAD

**Issue by duarteocarmo** [tw93/MiaoYan#181]
I would like to open a specific folder that already contains markdown files. Is this already possible? 

Thanks for the great work!

**Comment by tw93** [comment]
You can open the settings directly and select the storage location.

**Comment by duarteocarmo** [comment]
Ah very cool! Great work on this @tw93, absolutely love it.

**Comment by tw93** [comment]
Welcome to recommend it to your friends. At the same time, you can set up a nice English font in it.

**Comment by duarteocarmo** [comment]
I actually love LXGW WenKai Lite, looks super sharp. 谢谢！

**Comment by tw93** [comment]
Haha, me too. I like this font very much, so I took it as the default font.

**Comment by duarteocarmo** [comment]
It's absolutely awesome. I don't expect you to add any of these features! But would love if this app also had: 
- vim bindings
- some sort of automatic naming of new notes, zettlekasten style

Awsome work on this @tw93  :) Excited to see where you take it!

**Comment by tw93** [comment]
Thanks for your feedback. The vim will be put into the plan. For the second one, try the format option in the menu bar to see if it can meet your needs
