### ISSUE TITLE
使用PicGo图床上传成功，但是图片路径中部分符号编码导致路径错误

### ISSUE THREAD

**Issue by Ssiswent** [tw93/MiaoYan#182]
图片上传成功后，自动填写的链接不对，其中`:`和`/`是经过编码的

经测试，撤回自动填写的图片内容重新粘贴，链接就正确了
在Typora中使用也是一模一样的情况
但是VsCode的PicGo插件使用正常
请问有无解决办法呢，感谢~
<img width="1892" alt="image" src="https://user-images.githubusercontent.com/37449310/197723228-59343406-fca4-41db-be72-14f24d92609a.png">

**Comment by tw93** [comment]
这个你看看 PicGo 本身的配置，看看是不是设置有问题，同时辛苦试试 upic 可能更好用一些

**Comment by Ssiswent** [comment]
的确，是PicGo版本的问题，谢谢啦
<img width="616" alt="image" src="https://user-images.githubusercontent.com/37449310/197729619-47b3adb7-cc13-43ad-8092-2a8933a19d2d.png">
