### ISSUE TITLE
复制图片到笔记中的图片路径是绝对路径，PPT无法正常显示

### ISSUE THREAD

**Issue by brant-ruan** [tw93/MiaoYan#183]
如题，复制一个图片文件到笔记中，在妙言目录下自动创建了对应图片目录并复制了图片过去，同时笔记中出现的路径为：

```
![aptx4869](/i/610a59f2-cb48-4f8e-bcf1-77db3f0fd3b5.jpg)
```

预览模式能够正常显示图片：

<img width="691" alt="image" src="https://user-images.githubusercontent.com/13882906/197930677-6da96814-c244-47d0-82bb-70573c882acc.png">

但是PPT模式下无法正常显示图片：

<img width="497" alt="image" src="https://user-images.githubusercontent.com/13882906/197930706-973a0f3b-eea2-4f59-ae5f-56e7bb9a866f.png">

需要手动在绝对路径前加一个`.`变为相对路径，才能在PPT中正常显示：

```
![aptx4869](./i/610a59f2-cb48-4f8e-bcf1-77db3f0fd3b5.jpg)
```

系统版本：10.15.7
妙言版本：1.7.1

**Comment by tw93** [comment]
谢谢反馈 ppt下应该我没有注意到 我修复下

**Comment by tw93** [comment]
已经修复，着急可以试试这个包 https://static.tw93.fun/img/MiaoYan_beta.zip
假如没有问题，到时候就先发这个1.7.2的版本

**Comment by brant-ruan** [comment]
多谢，辛苦啦 :-)
