### ISSUE TITLE
Homebrew 安装 v1.7.1 无法使用

### ISSUE THREAD

**Issue by oxiran** [tw93/MiaoYan#188]
通过 **homebrew** 安装 MiaoYan，打开发现系统提示 "无法检查其是否包含恶意软件"。

<img width="264" alt="截屏2022-10-31 23 08 07" src="https://user-images.githubusercontent.com/31892817/199041840-aa10566f-0027-46ec-851a-84e3c9314302.png">

+ **mac 系统**：macOS Monterey 12.6
+ **芯片**：Apple M1 Pro
+ **MiaoYan 版本**：v1.7.1

**Comment by oxiran** [comment]
是否是证书问题？

**Comment by tw93** [comment]
试试在访达中打开，然后右键打开应该就好了
如果还有问题可以参考这个
https://zhuanlan.zhihu.com/p/135948430
