### ISSUE TITLE
希望能支持多级目录

### ISSUE THREAD

**Issue by gee1k** [tw93/MiaoYan#19]
希望能支持多级目录

**Comment by saup007** [comment]
so sad

**Comment by tw93** [comment]
@gee1k @JounQin @saup007 辛苦说说使用场景和不可或缺的理由哦

**Comment by JounQin** [comment]
@tw93 啊，大哥，为啥总是 @ 我，哈哈哈哈

**Comment by tw93** [comment]
> @tw93 啊，大哥，为啥总是 @ 我，哈哈哈哈
哈哈哈 你是半个开发者

**Comment by saup007** [comment]
> @gee1k @JounQin @saup007 辛苦说说使用场景和不可或缺的理由哦

主要最近几年用markdown笔记代替印象笔记，用目录做的类别管理，大概一、层级。
