### ISSUE TITLE
使用妙言的单独编辑器模式（隐藏笔记列表视图下）打开Markdown文件时，默认显示当前文件

### ISSUE THREAD

**Issue by koinzhang** [tw93/MiaoYan#191]
建议功能：使用妙言的单独编辑器模式（隐藏笔记列表视图下）打开Markdown文件时，默认显示当前文件

使用妙言单独编辑器模式时，在访达中打开一个markdown文件，并且隐藏妙言的笔记列表，打开后就只会突兀的显示下图，刚开始使用时很疑惑，以为是Bug，直到使用CMD+2显示笔记列表后才明白，妙言的单独编辑器模式不会默认显示打开的markdown文件，因此建议，在单独编辑器模式下，默认显示当前打开文件，如果不方便实现（请考虑改善当前情况，比如单独编辑器模式默认强制打开笔记列表）
另外，左下角的“单独编辑器模式下，按CMD...”的提示是否可以增加设置，让用户选择不显示（或者显示在菜单栏中），在我的使用过程中，大部份时间都是将妙言作为单独编辑器模式，所以这个提示有些冗余
<img width="800" alt="image" src="https://user-images.githubusercontent.com/36128970/199385377-b7bcd95e-b61f-4007-a483-c72c637cf459.png">

https://user-images.githubusercontent.com/36128970/199386438-a45e28e4-b67d-4b9e-829a-373267732113.mp4

**Comment by tw93** [comment]
谢谢反馈 我最近版本看看

**Comment by tw93** [comment]
已经修复，放到最近版本发布一起上线，预计这几天
主要为：
1. 单独打开文件的模式，只显示单独编辑器模式，不会出现侧边栏
2. 单独打开模式中不会出现提示toast，只有在有操作受阻的时候才会出现退出的模式提示
可以通过关注我的twitter 或者等到妙言的自动升级提示均可收到

**Comment by tw93** [comment]
已经修复，着急可以试试这个包 https://static.tw93.fun/img/MiaoYan_beta.zip
假如没有问题，到时候就先发这个1.7.2的版本

**Comment by koinzhang** [comment]
1. 使用beta包时有一个小问题，就是打开文件（单独编辑器模式下）时，会闪一下妙言的Logo（见下方视频），希望可以改进。

https://user-images.githubusercontent.com/36128970/201561695-a84ecd68-03ed-4c90-9eea-ec0cb2f6b9f7.mov

2. 遇到一次在单独编辑器模式下仍然没有默认打开文件的情况，无法复现

3. 使用妙言打开文件（单独编辑器模式下）时，dock栏图标会先消失再出现（见下方视频），还挺奇怪的，我理解是因为开了新的进程导致的？

https://user-images.githubusercontent.com/36128970/201562404-2edc7623-176b-4b05-9650-402fb4b780f1.mp4

4. 在后续版本能否考虑增加一个`在没有窗口打开时，自动关闭应用（单独编辑器模式下）`的功能，希望增加这个功能还是因为更倾向于把妙言当做一个编辑器，所以希望在关闭文档时，它可以自动退出

**Comment by tw93** [comment]
你直接更新最新包，当前已经更新到1.8.0版本，然后先打开来一次，然后再试试单独模式，应该会好一些，辛苦试试，保证你的Mac只有一个妙言，防止找的时候不太对

**Comment by koinzhang** [comment]
已更新1.8.0
上述问题1已改善，但仍会出现
问题2（见下图）、3仍存在

<img width="400" alt="image" src="https://user-images.githubusercontent.com/36128970/201569104-3b083eea-7e4c-42d3-86bb-496b9c6ea976.png">
