### ISSUE TITLE
是否有可能添加文件导出功能？

### ISSUE THREAD

**Issue by maclj** [tw93/MiaoYan#192]
类似于notion/ typora 的文件导出功能，导出如PDF/ Word之类的文件格式，有助于外部文档分享。这样就可以不仅仅作为个人的资料/ 笔记库了。

工具本身很好用，简洁方便。感谢你的辛苦付出~

**Comment by tw93** [comment]
有的，这个彩蛋你没有发现，其实很好用，找到需要导出的文章列表页面，右键，有一个导出，可以导出 pdf、图片、html文件，同时显示应该还挺好看的😂

**Comment by maclj** [comment]
找到了，相当不错，👍
