### ISSUE TITLE
找不到怎么切换脑图，找不到怎么使用Markmap

### ISSUE THREAD

**Issue by zxy12** [tw93/MiaoYan#194]
找不到怎么切换脑图，找不到怎么使用Markmap
<img width="830" alt="image" src="https://user-images.githubusercontent.com/4112803/202761530-74d932de-d367-4c45-8a5e-7b9ed62471e1.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/4112803/202761580-b62f40af-ea1b-499d-b97e-67e3466e1bb5.png">

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/blob/vercel/Release/demo/MiaoYan%20Markmap.md
参考看看

**Comment by zxy12** [comment]
解决了，非常赞
