### ISSUE TITLE
希望可以支持markdown导出 PDF 后分页的功能

### ISSUE THREAD

**Issue by shellRaining** [tw93/MiaoYan#197]
如题，如果我在文本中使用了
```html
<div STYLE="page-break-after: always;"></div>
```
妙言导出的 PDF 仅有完整的一张，不支持强制分页。我希望导出后的 PDF 具有分页的效果，特别是当内容特别多的时候整个 PDF 变成一个细长条状，比较难看。

还有就是如果导出为 HTML，最终打开的 HTML 文件中图片链接会失效

**Comment by tw93** [comment]
html模式下 图片地址建议使用cdn地址，因为导出的是一个html文件
pdf 分页这一块我看看，妙言使用的是 mac 底层组件的导出pdf的能力，还不一定支持分页配置，这个版本我看看，不能支持也会在这里回复你一下~

**Comment by CrossLee** [comment]
> html模式下 图片地址建议使用cdn地址，因为导出的是一个html文件 pdf 分页这一块我看看，妙言使用的是 mac 底层组件的导出pdf的能力，还不一定支持分页配置，这个版本我看看，不能支持也会在这里回复你一下~

这个 issue 有进展吗？我也遇到这样的问题，倒不是说样式难看，就是内容比较长的时候在手机应用里看 pdf ，字会被压缩的非常小。而且右边留白比较多，占版面的 1/3 了。

<img width="488" alt="image" src="https://user-images.githubusercontent.com/4584905/224462902-ff684a04-8afc-4e76-bd1a-d76421230fab.png">

**Comment by tw93** [comment]
终于解决啦，最近会发布一个版本 @CrossLee @shellRaining 
预计这周这几天，到时候辛苦关注更新通知
