### ISSUE TITLE
1.8.0演示功能似乎失效了

### ISSUE THREAD

**Issue by apache1011** [tw93/MiaoYan#199]
演示界面变成了这样（注意右下角的提示，确实是在演示模式）
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/27207036/205498367-10b9a272-c91b-4913-8260-46823667ed26.png">
如果按command+option+P，页面显示为空白

**Comment by tw93** [comment]
我试了试是OK的，你写一个最简单的看看，还有是不是没有联网

**Comment by apache1011** [comment]
退出app后重新打开恢复正常了，bug无法复现了lol，感谢回复

**Comment by tw93** [comment]
谢谢反馈哈
