### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by Tukali** [tw93/MiaoYan#2]
1.笔记的高度没法更改，很影响使用，并不是一定会使用全屏编辑的
2.笔记的字体和字号无法更改，可能不是所有人都能适应默认的字体
3.希望能增加快捷创建表格和简单的添加行列，合并单元格的功能
4.希望能增加对字体的颜色高亮（简单的几个颜色），还有一些简单格式快捷键（加粗、下划线等）
5.作者是否有想过适配m1mac呢，活动监视器看到是intel的，现在arm的用户应该越来越多了

**Comment by tw93** [comment]
很感谢你的反馈，很有道理
1. 是一个bug，问题早上已经修复，点击菜单栏检查更新到0.3.1即可
2. 2我尽快会加上常用字体的选择，预计下一个版本
3. 这个我想一想，基本的表格应该问题不大
4. 这个我逐步优化，对标vscode里面写md的体验
5. 想过，不过我当前不是M1，所以不好测试

**Comment by tw93** [comment]
当前已经支持字体的选择，字号的选择
关于3,4,5 后面再支持哦~
先关掉这个issue，我记住了待优化的问题

**Comment by Tukali** [comment]
> 当前已经支持字体的选择，字号的选择 关于3,4,5 后面再支持哦~ 先关掉这个issue，我记住了待优化的问题

好的，我会持续关注的
