### ISSUE TITLE
希望增加arm版本的安装包

### ISSUE THREAD

**Issue by Marszs** [tw93/MiaoYan#20]
如题

**Comment by tw93** [comment]
明天我看看，不麻烦就这个版本支持

**Comment by XIEJIAHAN** [comment]
复议+1

**Comment by Quixot1k** [comment]
希望能有apple silicon的arm包 +1

**Comment by JounQin** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/8336744/174442141-e093951f-e074-4213-9e63-cb9c53a66ad6.png">

不知道是不是因为作者用的不是 M1 的 Mac？我尝试本地构建了一下直接就是『通用』架构的。我是用 [`fastlane`](https://fastlane.tools) 打包的。

**Comment by tw93** [comment]
@JounQin 的确 我不是m1，不过我在最近版本已经配置好了，有办法帮忙打包一个出来不，让大家试试

**Comment by JounQin** [comment]
@tw93 非常乐意，可惜我是个 iOS/macOS 新手，我本地构建的时候由于签名原因只能把 developer team 和 org group 改了。See https://github.com/JounQin/MiaoYan/commit/b59ba752c517d4c37c68d161789f426b4bc2bd65

如果这些没关系且告知我如何构建 `.dmg` 的话可以很快打包一个出来。（我之前打包出来的是 `.app`）

**Comment by tw93** [comment]
可以将app发我试试

**Comment by JounQin** [comment]
[妙言.app.7z.zip](https://github.com/tw93/MiaoYan/files/8933804/app.7z.zip)

**Comment by tw93** [comment]
@Quixot1k @Marszs @XIEJIAHAN 帮忙看看0.5.0的版本是不是兼容ARM64的
话可以下载这个刚刚 @JounQin 帮忙打包的试试
https://qpluspicture.oss-cn-beijing.aliyuncs.com/wgTzfU/MiaoYan-V0.5.0-ARM64.dmg

**Comment by tw93** [comment]
@JounQin 打好了，你看看上面链接下载看看

**Comment by JounQin** [comment]
> @JounQin 打好了，你看看上面链接下载看看

OK 的

**Comment by tw93** [comment]
> > @JounQin 打好了，你看看上面链接下载看看
> 
> OK 的
> 
> 另外我正在将 MiaoYan 提交到 homebrew-cask [Homebrew/homebrew-cask#125999](https://github.com/Homebrew/homebrew-cask/pull/125999)

👍🏻

**Comment by JounQin** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/8336744/174514374-97ad561a-b6f9-4781-859e-f2f433d8b3b5.png">

@tw93 最新版仍然有问题，Intel 的 mac 那儿有『种类』显示么？

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/174515399-c2137eb6-609b-473a-a7bf-8fb7db7fb4a4.png)
@JounQin 有的，还是这个
打arm64的包必须是M1的mac吗？

**Comment by JounQin** [comment]
> 打arm64的包必须是M1的mac吗？

😅 可能是？。。。我也没有相关经验

**Comment by tw93** [comment]
终于支持通用架构了了，可菜单栏检查更新升级最新版本体验
https://github.com/tw93/MiaoYan/releases
@JounQin @XIEJIAHAN @Quixot1k @Marszs
