### ISSUE TITLE
新功能投票

### ISSUE THREAD

**Issue by whsheng** [tw93/MiaoYan#200]
非常喜欢「**妙言**」这款产品，界面美观 、功能简单好用，作者更新很频繁。自己使用过程中，希望能有如下功能：

1. 导出的PDF支持分页
2. 导出的文件支持加水印
3. 支持tag或目录分级，便于文件快速查找
4. 支持对指定文件加密访问
5. 支持对指定文件的历史版本管理
6. 支持一键呼出「快捷键/帮助」，感觉妙言的功能很简单，但很多小技巧不知道怎么使用？

**Comment by luo-h** [comment]
希望增加账号体系，资源存储，换电脑不好迁移啦
