### ISSUE TITLE
图片添加

### ISSUE THREAD

**Issue by whsheng** [tw93/MiaoYan#201]
现有的「妙言」支持直接复制图片到文档中，自动将图片保存到当前文档同级的子目录i中，这个功能很好用，点赞！

使用过程中，有几个小建议：
1、添加的图片，能否参考typora，可设定图片显示的大小、位置（居中、靠右等）；
2、在编辑文档中，当输入![]()的时候，能否自动显示当前目录下可使用图片？

暂想到这么多！请作者参考！
@tw93

**Comment by tw93** [comment]
感谢反馈，这个我看看实现
