### ISSUE TITLE
有个疑惑.. 不知道当讲不当讲？！

### ISSUE THREAD

**Issue by hongquan66** [tw93/MiaoYan#202]
我追了很长时间的一个up主推了一款自家公司自研的笔记工具，也曾试用一段时间
但是我看到你的项目时，似曾相似的感觉一下就来了
[https://www.effie.co](https://www.effie.co) 有兴趣可以看看，不知道有没有啥商业合作，但是功能重叠度确实有点高

**Comment by tw93** [comment]
没有商业合作哈，哈哈 内涵还是不一样的，其实你看妙言和mac默认的备完录也长一样，只不过这是笔记应用的默认结构而已
