### ISSUE TITLE
请问，妙言可以左边编辑，右边同步预览吗？

### ISSUE THREAD

**Issue by ganwt** [tw93/MiaoYan#205]
你好，很喜欢妙言这款软件。
可以在iCloud里同步，又可自行管理md文件，这个创意简直太棒了。

作为md的初心者，对md的语法不是很熟练的情况下，在使用过程中，察觉边输入边预览的功能很有帮助。
不知道miaoyan如何把页面变成**左边编辑，右边同步预览**的状态，Google先生找了一下，暂时还没有找到相关的教程。
- 所以冒昧前来提交以下两点功能请求。

1. 像vscode一样，可以左边编辑，右边同步预览。
2. 像GitHub的编辑页面一样，增加几个简单的插入md语法的功能图标。
3. 标题栏按回车键不自动换行。（日语输入法回车键是选定，会导致输入变得困难）

- 更加冒昧，请原谅：
如果可以帮助miaoyan翻译/增加日语版的话，很乐意效劳哦。

**Comment by tw93** [comment]
> 如果可以帮助miaoyan翻译/增加日语版的话，很乐意效劳哦

哇 完全可以的

关于你说的那个应该是双栏编辑，其实有有一个feature在弄，是即时渲染，不过稍微有些慢了

**Comment by ganwt** [comment]
> 哇 完全可以的，不过需要我将代码结构这两天整理一下，你就可以开始了
感谢。荣幸可以贡献一份绵薄之力。
期待双栏编辑的即时渲染功能。

**Comment by tw93** [comment]
Is it convenient for you to add my telegram?  @hitw93
Let's talk about Japanese translation 🎉

**Comment by tw93** [comment]
这一块已经联系上同学，此外在帮忙做日文翻译，后面直接聊天沟通即可
