### ISSUE TITLE
PPT 分栏

### ISSUE THREAD

**Issue by yym68686** [tw93/MiaoYan#206]
希望 PPT 可以分成左右两栏，左边内容多了，可以自动转到右边列显示。

现在的情况是内容多了，会显示不全。

**Comment by tw93** [comment]
是的，这里比较建议用css来控制，是完全支持的
你说的这个左右分栏我想想办法哈

**Comment by tw93** [comment]
优化了一波，超过的内容自动支持可以滚动，最近两天给发布一个版本，请关注release
