### ISSUE TITLE
插入图片的功能优化

### ISSUE THREAD

**Issue by fanpeizhou** [tw93/MiaoYan#208]
问题描述：目前插入图片的过程不是很方便，也可能是我操作不当。
个人想法：妙言的设置里是可以设置图床的，但我并没有get到它。我还是要手动把图片上传到图床（例如Upic）然后接受URL，再插入到Markdown文本。不是我以为的直接拖入图片然后根据设置的图床自动接收URL自动插入图片（把图片存入iCloud的方式不好将文档分享给他人）。不知作者是否有兴趣优化此流程？

**Comment by tw93** [comment]
这个支持的，设置图床的前提是你本地给配置好了对应图层
然后可以在设置里面打开，可以试试copy一张图片，然后在妙言里面粘贴，应该就会帮你自动上传，并替换成cdn地址
