### ISSUE TITLE
关于 Tab 下的一个bug

### ISSUE THREAD

**Issue by keyding** [tw93/MiaoYan#210]
在代码块中，按 Tab 键，光标没有移动，但其实 Tab 已经生效了。

```
const mayBeBug = () => { 
                    console.log()
}
```

https://user-images.githubusercontent.com/20431351/211976848-8395214b-a433-4393-a76b-84ff27faf5df.mp4

Version: 1.8.0

**Comment by tw93** [comment]
谢谢反馈 我应该过年前后发一个中位数版本

**Comment by tw93** [comment]
tab 问题统一合并到这个issue，这个先关闭
https://github.com/tw93/MiaoYan/issues/193
