### ISSUE TITLE
Markmap 对 markdown 语法支持

### ISSUE THREAD

**Issue by overlookart** [tw93/MiaoYan#215]
目前 Markmap 只支持以代码块的方式编辑 ,可以做到对 markdown 语法的支持吗？

参考 VSCode 插件 Markmap： https://markmap.js.org

**Comment by tw93** [comment]
可以理解成将整个文档渲染成 脑图吗？

**Comment by overlookart** [comment]
是的

**Comment by tw93** [comment]
抱歉 这个功能我想了想和整体 markdown 功能会有一定违背，这一块假如需要使用，智能全页加载代码包裹起来了
