### ISSUE TITLE
无法关闭单独编辑器模式

### ISSUE THREAD

**Issue by kankk** [tw93/MiaoYan#218]
Mac系统中在单独编辑器模式中按 `Command + Shift + W` 也无法关闭单独编辑器模式回到原本的模式。

现在情况是怎么也无法退出单独编辑器模式回到原本文件夹目录的模式，是否可以考虑在状态栏加一个关闭/切换单独编辑器模式的选项？

**Comment by tw93** [comment]
有必要，最近版本我加一下，假如你这种情况，可以试试 command+q 然后重新打开即可

**Comment by kankk** [comment]
Nice！
