### ISSUE TITLE
众多快捷键助你快一步？

### ISSUE THREAD

**Issue by a523** [tw93/MiaoYan#22]
我想了解下有哪些快捷键， 以及在哪里可以查看到， 我想要一个快速预览的快捷键， 没找到。
也没找到可以自定义快捷键的设置选项

**Comment by sbccznfy** [comment]
可以在视图标签栏中看到，预览快捷键是command+3

**Comment by tw93** [comment]
@a523 @sbccznfy 正解
大家有需要的快捷键都可以提issue
快捷键爱好者是同类人哈哈
