### ISSUE TITLE
预览字体异常

### ISSUE THREAD

**Issue by superRaytin** [tw93/MiaoYan#221]
应用开着一段时间后，预览的字体貌似会自动被重置为类似 Arial 这样的默认字体：

<img width="406" alt="image" src="https://user-images.githubusercontent.com/2723376/221080691-147045e5-eaab-4566-a591-98e540ec31eb.png"> <img width="423" alt="image" src="https://user-images.githubusercontent.com/2723376/221080771-ac24642f-78ce-441a-9731-8049906454db.png">

一般到第二天就会这样，这时候我必须重启一下 App，预览字体才能恢复正常：
<img width="417" alt="image" src="https://user-images.githubusercontent.com/2723376/221081458-d144ba0a-f6a1-4ef3-b9d6-6c4c4156d2b7.png">

- App：最新 1.8.0 版本
- 系统：Mac OS X 11.2.3（M1）

**Comment by 56496477** [comment]
我也遇到了这个问题，并且预览的mermaid图不能显示

**Comment by tw93** [comment]
@56496477 试试最新的版本 1.9

**Comment by superRaytin** [comment]
> @56496477 试试最新的版本 1.9

@tw93 升级到 1.9 之后，预览字体的问题还在

**Comment by tw93** [comment]
在妙言打开偏好设置，辛苦看一看当前的预览字体对不对
<img width="560" alt="image" src="https://user-images.githubusercontent.com/8736212/225684931-29148b3f-f2db-468d-8089-943d9b57e534.png">

@superRaytin @56496477

**Comment by superRaytin** [comment]
@tw93 
![miaoyan-preview-issue](https://user-images.githubusercontent.com/2723376/225798063-6a72cd79-7963-4c41-b62a-f27c21b3fe55.gif)

**Comment by Miiw9790** [comment]
> 在妙言打开偏好设置，辛苦看一看当前的预览字体对不对 <img alt="image" width="560" src="https://user-images.githubusercontent.com/8736212/225684931-29148b3f-f2db-468d-8089-943d9b57e534.png">
> 
> @superRaytin @56496477

+1, 同更新到1.9后依然有问题，预览的字体不是默认字体，但是渲染的是
<img width="983" alt="image" src="https://user-images.githubusercontent.com/128283163/226169698-4e5885f6-1d6e-4818-89b2-0ab840f61cf8.png">

**Comment by tw93** [comment]
@superRaytin @56496477 @Miiw9790  下次出现了辛苦帮忙试试，在当前预览页面右键 `重新载入`，看是否变好，看起来不是字体问题，而是容器被回收了一样，不过我这边周末尝试了挺久，不能到这样
<img width="194" alt="image" src="https://user-images.githubusercontent.com/8736212/226183203-4bf6c6f1-60d6-40c0-9df1-0a00930f3ba7.png">

**Comment by Miiw9790** [comment]
> @superRaytin @56496477 @Miiw9790 下次出现了辛苦帮忙试试，在当前预览页面右键 `重新载入`，看是否变好，看起来不是字体问题，而是容器被回收了一样，不过我这边周末尝试了挺久，不能到这样 <img alt="image" width="194" src="https://user-images.githubusercontent.com/8736212/226183203-4bf6c6f1-60d6-40c0-9df1-0a00930f3ba7.png">

点击了重新载入还是有问题的

**Comment by tw93** [comment]
@Miiw9790  谢谢，我再想想办法

**Comment by lzcdev** [comment]
遇到同样的预览字体问题，连续用了几天没关之后出现的。
- App: 1.9.0
- 系统：macOS Big Sur 11.2.3 (M1)

**Comment by tw93** [comment]
@lzcdev  请问最小化的时候，是不是也是保持着预览模式的打开，还是一直是编辑模式，最后使用出现了预览字体的问题？

**Comment by tw93** [comment]
做了一个性能优化，当妙言最小化以后，超过半小时会进行预览下的内存回收，可以防止掉这个问题，预计最近2天发布一个版本

**Comment by superRaytin** [comment]
升级到最新版本 1.10.1，这个问题还在 👀
