### ISSUE TITLE
自定义快捷键以及导出文档目录

### ISSUE THREAD

**Issue by PeiLeiScott** [tw93/MiaoYan#223]
首先感谢作者开发的这款软件，颜值相当高！

希望能够支持以下两个功能：
1. 目前快捷键都是固定的，希望支持用户自定义
2. 导出文档目录为Desktop，希望支持任意目录

**Comment by tw93** [comment]
最近会发布一个版本，将原有文档直接导入到下载目录，支持任意目录会有一个弹框会容易干扰用户（我理解哈）
快捷键这一块当前主要是哪一些需要自定义？

**Comment by quanru** [comment]
同求：自定义快捷键
