### ISSUE TITLE
能否增加文件文档目录结构

### ISSUE THREAD

**Issue by NothingOnYouMoon** [tw93/MiaoYan#225]
能否增加一个文档目录结构的功能，支持新建多级文件夹
<img width="233" alt="image" src="https://user-images.githubusercontent.com/17716916/225506673-c56737f3-5f40-43f1-a3a5-5aa9b2625b11.png">
类似于这种文件目录结构有助于管理上百甚至上千份md文件，并且方便从其他平台直接复制md文件夹过来，自动形成相应的目录。
谢谢作者

**Comment by tw93** [comment]
issue 整理，和这里这个是一个需求，先放这里
https://github.com/tw93/MiaoYan/issues/225
