### ISSUE TITLE
开启预览后再开启演示模式时，无法退出演示模式

### ISSUE THREAD

**Issue by Fizell** [tw93/MiaoYan#226]
**设备:** MacBook Pro 14 寸 2021, M1 Pro
**版本:**  [V1.10.1](https://github.com/tw93/MiaoYan/tree/V1.10.1)
**复现:**
1. 开启预览
![image](https://user-images.githubusercontent.com/38578669/229061674-7992aa59-724a-4a92-b84b-3897b453cf9a.png)

2.开启演示模式
![image](https://user-images.githubusercontent.com/38578669/229061904-adc49d3e-9f6f-4d84-b4e6-3d5eb2708d6f.png)

3.退出演示模式(ESC或者点击右上角)
异常: 点击后没有反应，无法回到第一步时的页面状态
![image](https://user-images.githubusercontent.com/38578669/229062017-47adb22d-bc93-4992-8fdb-1d45a97e5c4e.png)

**Comment by tw93** [comment]
谢谢反馈 我修复下

**Comment by tw93** [comment]
已修复，最近一个版本发布，预计在这周，请关注更新日志即可
