### ISSUE TITLE
预览有时字体不对

### ISSUE THREAD

**Issue by Likelihoood** [tw93/MiaoYan#228]
最新版本，
Version 1.10.1

**Comment by tw93** [comment]
是放置久了以后还是 方便给一下系统版本吗

**Comment by Likelihoood** [comment]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/814343/231801815-74eca51e-5080-4550-ab0c-9368cfb69fad.png">

**Comment by jykSS** [comment]
我的也出现这个问题了,还不太好复现,重启电脑就好了

**Comment by tw93** [comment]
我优化了一个版本，最近会发布一下，请关注最新的更新，预计这几天了。
