### ISSUE TITLE
行首输入多个连续空格导致软件无响应

### ISSUE THREAD

**Issue by lorcannn** [tw93/MiaoYan#232]
MiaoYan Version 1.10.1
MacOS 12.5(M1)

![1683208919535-20230504_215843](https://user-images.githubusercontent.com/56643497/236231445-c39628a2-5cc8-44d8-a898-be3136bcc406.gif)

**Comment by tw93** [comment]
谢谢反馈 已经修复，预计这周发布一个版本，请关注最近的更新
