### ISSUE TITLE
打开一个md格式文件后，之前随手记录的内容大部分丢失，不知道从哪里找回

### ISSUE THREAD

**Issue by wangb259** [tw93/MiaoYan#233]
🙊辛苦提 bug 前，去找一下 [历史的](https://github.com/tw93/MiaoYan/issues?q=) 是否有提，同时检查一是否为最新版本。辛苦提供版本号、录屏或者截图、复现路径，期待解决的点这几个说明帮助我更好的解决问题。提交前请删除这些文字。<br>
🙊Look for [issue](https://github.com/tw93/MiaoYan/issues?q=) before you mention bugs Whether it is mentioned, and check whether it is the latest version. Need to provide the version number, screen capture or screenshot, reproduction path, and look forward to the points to be solved. These instructions help me better solve the problem. Please delete these words before submitting.

**Comment by tw93** [comment]
可以通过command+shift+w 退出单独模式，或者直接command+q 退出即可

**Comment by wangb259** [comment]
【已解决】感谢！通过command+shift+w 退出单独模式

Tw93 ***@***.***> 于2023年5月5日周五 10:57写道：
