### ISSUE TITLE
笔记列表中文件名显示不全

### ISSUE THREAD

**Issue by RANSAA** [tw93/MiaoYan#234]
如题笔记列表中的文件名显示不全，作者可以把它做成多行显示。

**Comment by tw93** [comment]
抱歉，我是一个强迫症患者，你可以试试在竖线这一块拉动一下，然后拉长一些就好，多行显示美观上不好看。
<img src=https://github.com/tw93/MiaoYan/assets/8736212/ba15f870-5b01-4dfc-b9d2-7af2617409f2   width=300 />
