### ISSUE TITLE
希望增加一个选项可以决定是否开启自动排版

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [tw93/MiaoYan#240]
自动排版会搞乱无序列表，但有时预览时又不小心摁到，所以能不能在选项中增加决定是否开启自动排版，一旦关闭在界面上就没有这个按钮，麻烦了

**Comment by shoudeyunkaijianyueming** [comment]
<img width="1371" alt="image" src="https://github.com/tw93/MiaoYan/assets/71814666/7dde110b-fca1-451d-be06-45970c224922">
这是原先的

**Comment by shoudeyunkaijianyueming** [comment]
<img width="1133" alt="image" src="https://github.com/tw93/MiaoYan/assets/71814666/58cc32e8-a1fc-459d-a4b8-e8dc770494bc">
这是原先的

**Comment by shoudeyunkaijianyueming** [comment]
这是自动排版后的
<img width="1285" alt="image" src="https://github.com/tw93/MiaoYan/assets/71814666/658415e8-0bd7-4078-8ffb-68a56b66a695">
如果能修复这个问题，当然好，如果不能增加一个关闭按钮，感谢

**Comment by shoudeyunkaijianyueming** [comment]
<img width="430" alt="图片" src="https://github.com/tw93/MiaoYan/assets/71814666/bffd044f-3350-42bb-adba-26d3c7701542">

不仅仅是这个格式问题，这样的格式也不行

**Comment by shoudeyunkaijianyueming** [comment]
[toc]
- **思维导图** #04conclude
- **知识点**
	- 如何判断是否是民事法律关系
	- 民法调整的人身关系
	- 民法调整的财产关系

**Comment by shoudeyunkaijianyueming** [comment]
<img width="747" alt="图片" src="https://github.com/tw93/MiaoYan/assets/71814666/7f8026c1-9e6b-4080-9d8b-93804b778cdb">

格式后变成了这样的

**Comment by shoudeyunkaijianyueming** [comment]
要不老哥增加个关闭按钮，防止误触，毕竟格式并不是每个人都需要的

**Comment by tw93** [comment]
有道理 这里还有一个解法 可以在设置里面隐藏按钮，然后使用快捷键的方式，比如说预览是 command ➕ 3 你试试这样满足不

**Comment by shoudeyunkaijianyueming** [comment]
可以，麻烦老哥了

**Comment by tw93** [comment]
你去试试，应该现在就支持，先去设置配置下

**Comment by shoudeyunkaijianyueming** [comment]
现在的应该是浮动hover吧，能不能有个彻底隐藏的选项呢

**Comment by tw93** [comment]
是的 因为单独隐藏做是好做，但是我其实格式化是妙言的一个亮点功能，这样你先使用快捷键来预览，假如后面还是容易误操作，我就来想一个办法
