### ISSUE TITLE
导出“妙言 PPT PDF”时显示不全及排版错误

### ISSUE THREAD

**Issue by hrtdream** [tw93/MiaoYan#241]
版本号 1.10.1
macOS 13.4.1
问题描述：在对示例的“妙言 PPT”导出为“妙言 PPT PDF”时，会出现内容显示不全以及排版错误的情况

<img width="1869" alt="CleanShot 2023-06-25 at 14 24 16@2x" src="https://github.com/tw93/MiaoYan/assets/54263732/eb93673d-2195-4ee9-9a48-28014cfdba7a">

<img width="1869" alt="CleanShot 2023-06-25 at 14 24 26@2x" src="https://github.com/tw93/MiaoYan/assets/54263732/08ede98d-76d8-4bb9-a52b-c6c80497980c">

<img width="1869" alt="CleanShot 2023-06-25 at 14 24 35@2x" src="https://github.com/tw93/MiaoYan/assets/54263732/a560e6ee-ea54-460d-b627-7ee6a16020bd">

**Comment by tw93** [comment]
谢谢反馈 我看看，请问这个是用显示器预览导出的吗？试试电脑屏幕是不是ok的

**Comment by hrtdream** [comment]
是的，是通过4k显示器导出的，用笔记本屏幕导出的话也会有同样的问题。设备是 MacBook Pro 16寸
<img width="1834" alt="CleanShot 2023-06-26 at 10 04 22@2x" src="https://github.com/tw93/MiaoYan/assets/54263732/0101440c-ffc1-41c7-9b8a-1a04e9377498">

<img width="1834" alt="CleanShot 2023-06-26 at 10 05 04@2x" src="https://github.com/tw93/MiaoYan/assets/54263732/e3cf103d-72a1-48ad-bda5-9829ebf2b88a">

<img width="1834" alt="CleanShot 2023-06-26 at 10 05 34@2x" src="https://github.com/tw93/MiaoYan/assets/54263732/df9958b1-bf0d-490e-9c5e-229a8954b8cb">

**Comment by hrtdream** [comment]
另还想问下，多行数学公式的渲染还是需要通过
`<div>$$\begin{cases} x&=1\\ y&=2\end{cases}$$</div>`
来实现吗？目前多行数学公式还是不能正常显示，仍需要添加
`<div>...</div>`
谢谢！

**Comment by tw93** [comment]
添加 div 是正常的，span 应该也行

**Comment by tw93** [comment]
我应该修复了，这两天会发布一个新版本，辛苦关注最新的release公告更新即可
