### ISSUE TITLE
切换到预览模式时总是从文章开始预览

### ISSUE THREAD

**Issue by sbccznfy** [tw93/MiaoYan#25]
每次预览都是从第一行开始看，可不可以自动定位到当前正在编辑的位置，这样就不用每次都向下滑动很长的距离

**Comment by tw93** [comment]
好建议，这一块我想想产品实现，因为很多人也习惯从开始看，所以这里会有一个选择

**Comment by tw93** [comment]
我想了想还是不太对的样子，你这个功能更适合放到编辑+预览双栏布局这个场景里面去，我先记着
