### ISSUE TITLE
添加一个 "打开md文件默认是预览模式" 的设置选项

### ISSUE THREAD

**Issue by niuxiangchen** [tw93/MiaoYan#253]
希望您能添加一个 "双击打开文件默认是预览模式的" 设置选项
作为一个学生，对于md文档我更多是阅读而不是写作
每次打开md文件还要手动切换到预览模式不太方便
感谢！

**Comment by tw93** [comment]
先 command + 3，然后直接点击切换就好了

**Comment by niuxiangchen** [comment]
@tw93  版本号是最新版本1.11.0
我的关注点在于 "默认"
比如说我第一次打开A文件，我需要通过cmd+3 切换为预览模式
我关闭A文件后 第二次打开时 仍然是编辑模式 ，我还是需要cmd+3再切换一次
我期望的功能是 当我勾选了“默认以预览模式打开” 这个选项后，每次打开时都是预览模式

**Comment by tw93** [comment]
有没有类似的产品是这样做的？我去看看产品思路
感觉是不是语雀会更合适

**Comment by niuxiangchen** [comment]
类似于typora 语雀那样
但是不需要做到 边编辑边渲染 的所见即所得的效果
只需要 我一打开文件能直接看到预览的效果 而不是md源代码 (即打开文件自动切换到预览模式)

我理解的话 只需要给用户在设置里提供一个选项
默认以预览模式打开 或者是 默认以编辑模式打开

**Comment by tw93** [comment]
谢谢反馈，我已经添加，请等下一个版本更新，1.13.0，不需要设置，默认打开会记住上一次的，持久化记忆，也就是即使重新启动也会记住你的下一次，请等待妙言正式版本发布

**Comment by LittleSource** [comment]
默认打开会记住上一次的，持久化记忆。貌似这个在4.2.0并没有默认打开会记住
