### ISSUE TITLE
链接的本地文件无法打开?

### ISSUE THREAD

**Issue by eggb4by** [tw93/MiaoYan#255]
比如有一个文件是/Users/xxx/Documents/MiaoYan/论文/ahp-fce/基于改进层次分析法的模糊综合评价模型_金菊良.pdf
然后我的markdown内容是
| 文件名 | 年份 | 分类 | 被引 | 链接 | 
| ---------- | ----------- | ----------- | -----------| ----------- |
| 基于改进层次分析法的模糊综合评价模型_金菊良 | 2004 | AHP-FCE | 1078 | [链接](/Users/xxx/Documents/MiaoYan/论文/ahp-fce/基于改进层次分析法的模糊综合评价模型_金菊良.pdf) |

preview的页面没什么问题，但是点击链接或者右键在新窗口打开，都无法打开这个文件
PS:这个文件我直接浏览器输入这个地址打开是正常的

**Comment by tw93** [comment]
这里看了一下是本地的文件，预览页面你可以理解成一个web容器，好比浏览器一样的内核，浏览器输入是由于本地和文件系统打通了导致，这里其实很建议你可以将pdf存到其他cdn或者可以访问地方，然后点击打开
