### ISSUE TITLE
有可能加入图床支持吗

### ISSUE THREAD

**Issue by jinfagang** [tw93/MiaoYan#26]
例如picgo

**Comment by tw93** [comment]
有计划，不过会先放到当前主体编辑器功能好用以后的优化功能，比如说后面支持pdf、图片、html导出这种

**Comment by tw93** [comment]
@jinfagang 图床已OK
https://github.com/tw93/MiaoYan/releases/tag/V0.7.0

**Comment by imaxing** [comment]
> @jinfagang 图床已OK https://github.com/tw93/MiaoYan/releases/tag/V0.7.0

hi, 大佬你好~ 
图床有没有计划增加一个自定义配置
比如当我粘贴后将调用自己的上传脚本上传到自己的oss上, 然后返回oss的地址给到妙言进行展示 😄

**Comment by tw93** [comment]
这个默认支持，只不过1.6版本我优化一个配置时候影响了，你试试https://fl-file.oss-cn-hangzhou.aliyuncs.com/plUDlq/妙言.app.zip
