### ISSUE TITLE
希望增加字數統計功能

### ISSUE THREAD

**Issue by aaron2wh** [tw93/MiaoYan#263]
🏂 很感谢你给妙言提建议，辛苦将你的需求描述清楚一些，特别期待你可以说明白这个功能很有用，没有加这个功能会让你很遗憾。提交前请删除这段文字。<br>
🏂 Thank you for your advice to MiaoYan. Need you describe your needs clearly. I especially hope you can make it clear that you will regret not adding this ability. Please delete this text before submitting.

因為我每次寫作的文章需要字數標準，word狀態欄實時可見，心理比較有譜，寫了多少，還差多少。希望妙言增加這個功能，我就可以從Word轉陣營了。

這個字數無論包括MD語法代碼與否都無所謂。當然如果可選是否包括更好。

**Comment by tw93** [comment]
字数统计这个功能有的，试试右键文章item，会有一个「显示简介」统计字数

**Comment by aaron2wh** [comment]
哦，挺好的，能做成寫作的時候實時顯示嗎？這樣就少了兩次點擊，懶癌犯了😂

**Comment by aaron2wh** [comment]
另外還有一條小bug，不知道是否算bug，就是當隱藏筆記列表時，使用快捷鍵(cmd+opt+i) 也無法喚出字數統計。 如果實時顯示字數比較難實現的話，退而求其次，可以做到隱藏列表時可以使用快捷鍵喚出字數統計也是善事一件哈
