### ISSUE TITLE
新建文件夹无法正常显示，且新建的md文件目录不在miaoyan文件下

### ISSUE THREAD

**Issue by shellGrace** [tw93/MiaoYan#265]
使用版本 version 1.11.0
1. 新建md文件默认散落的存储在「文稿」下，而不是之前的 miaoyan 文件夹下
2. 在妙言新建文件夹，新建成功后文件夹存在 文稿 目录下，但妙言未显示出文件夹
3. 新建的文件夹/已有文件夹 拖拽文件夹到妙言无法打开

ps: 不清楚是不是我自己电脑本身默认路径被改了

**Comment by tw93** [comment]
是的，你试试command+. 打开设置看看，里面可以配置

**Comment by shellGrace** [comment]
重新配置了路径后，文件的存储位置已解决，但还存在以下两个问题：
1. 在妙言新建文件夹，新建成功后妙言未显示出文件夹
2. 拖拽文件夹到妙言无法打开
<img width="395" alt="image" src="https://github.com/tw93/MiaoYan/assets/46156180/6dced20e-7095-489c-a287-4129556bf954">

**Comment by tw93** [comment]
需要确定一下新建的文件夹下面是否有文件，更建议通过顶部+来创建文件夹试试

**Comment by shellGrace** [comment]
是的，我是通过+号新建的，已经找到问题原因。下载的安装包默认继承了以前的设置（或是原本就预设了），我重新翻看了issue 历史回复，通过 command+shift+w 解决了文件显示问题，感谢回复～

**Comment by tw93** [comment]
好勒 谢谢！ 欢迎多提提建议，也欢迎参与进来开发
