### ISSUE TITLE
uPic 设置好了，但是粘贴照片到妙言还是失败了

### ISSUE THREAD

**Issue by Penggeor** [tw93/MiaoYan#270]
你好，妙言是非常棒的软件 👍
我这边遇到情况是下载并且设置好了 uPic，设置 host 并且 validate 上传图片也是成功的。
但是在妙言这边粘贴图片之后，却还是失败了。（已经尝试重启 uPic 和妙言）

<img width="1280" alt="image" src="https://github.com/tw93/MiaoYan/assets/68799055/5915b1d0-e2bb-4eb2-8131-225be3e50b28">

**Comment by tw93** [comment]
谢谢喜欢
我刚刚本地试了试是 ok 的，有一种可能，是不是你的图片太大了，你可以试试传一张小图片试试看是否成功

**Comment by Penggeor** [comment]
定位到原因了，我虽然下载安装了 uPic，但是很奇怪它没有出现在我的 Application 中，导致妙言找不到。
解决方法现在就是手动把 uPic 拖动到 Application 文件夹中。
