### ISSUE TITLE
Tray App 形式

### ISSUE THREAD

**Issue by Lpmvb** [tw93/MiaoYan#271]
期望能添加 Tray App 形式，支持在 Menubar 处唤起/隐藏 App

**Comment by tw93** [comment]
这里我更建议通过 command+shift+m 这个功能来唤起隐藏妙言，说实话我不是特别喜欢将icon放到顶部菜单栏，感觉有些乱
此外也很建议直接使用 raycast 来设置全局快捷键，即使妙言没有开启，也可以唤起
