### ISSUE TITLE
编辑模式到预览自动换行显示问题

### ISSUE THREAD

**Issue by Sherlock-Xpf** [tw93/MiaoYan#274]
hi tw93。我这边发现的问题，想反馈下。

从编辑模式切换到预览模式后，原本编辑模式下的两行或多行内容直接变成一行内容。

是换行符被替代了么？还是我配置的有问题？

**Comment by tw93** [comment]
<img width="171" alt="image" src="https://github.com/tw93/MiaoYan/assets/8736212/7a44b800-0c91-4f32-b9d4-878742cbe207">
是不是把这里修改成了 GitHub，改成miaoyan 这个选项即可，假如有问题，可以继续打开这个issue，然后给我可以复现的源文件md即可
