### ISSUE TITLE
一直用妙言

### ISSUE THREAD

**Issue by JimWang-happy** [tw93/MiaoYan#277]
1. 不能很好的在左侧显示文件目录
2. 希望支持一下文件排序(例如: 3th.md 5th.md 1th.md 自动排序后为 1th.md 3th.md 5th.md)
3. 左侧也不够显示文件夹目录，无论如何我怎么操作，比如我把目录拖进妙言，是不支持的
![image](https://github.com/tw93/MiaoYan/assets/76657138/7442ed75-8341-4188-895f-ada7dbcbca45)

**Comment by VomPom** [comment]
same issue
因为拖拖动了一下其他 .md 文档 到编辑器之后，原来存在的文件夹不再显示，新建文件夹也不会再显示，卸掉应用再重装也不会再显示
<img width="681" alt="image" src="https://github.com/tw93/MiaoYan/assets/27652454/a81522b0-9f8b-4498-a8bc-f6e6a1550c99">

**Comment by tw93** [comment]
应该都在的，你试试 command+1

**Comment by JimWang-happy** [comment]
操作 command+1 出现右下角提示


再操作右下角提示回到妙言介绍的文档，我的这个test也关闭，重新打开test还是一样
| |
wangyinxiang1019
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月28日 14:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [tw93/MiaoYan] 一直用妙言 (Issue #277) |

应该都在的，你试试 command+1

**Comment by JimWang-happy** [comment]
还是不行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月29日 19:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tw93/MiaoYan] 一直用妙言 (Issue #277) |

command+q 重新退出看看，你的上一个回复的图片看起来没有发出来

**Comment by tw93** [comment]
这里可以试试视图里面的排序方向，设置成按照文件名称来
<img width="290" alt="image" src="https://github.com/tw93/MiaoYan/assets/8736212/c6a2c224-c414-4021-8337-adab5ec429f6">
