### ISSUE TITLE
能否支持目录导航，类似Toc

### ISSUE THREAD

**Issue by jonnywang** [tw93/MiaoYan#28]
能否支持目录导航，类似Toc

**Comment by tw93** [comment]
截图给一个案例看看，类似语雀那种吗？

**Comment by tw93** [comment]
想了想，toc这种功能我还没有想太清楚，怎么既简洁又功能满足，假如你有好方案，可以提供出来，这个先关闭

**Comment by zwmmm** [comment]
长文章 感觉还是有必要展示 `toc` 的 可以默认隐藏 只给一个悬浮的提示 能够打开查看目录
