### ISSUE TITLE
能否实现对hookmark软件深度链接的支持

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [tw93/MiaoYan#281]
目前妙言就支持hookmark但是，无法做到深度链接，您能不能做个适配（如果有可能的话）

**Comment by tw93** [comment]
深度主要是指？辛苦给我一个具体的case

**Comment by shoudeyunkaijianyueming** [comment]
1、录屏了链接: https://pan.baidu.com/s/1k2XDFsmfZsgHfkd02te6nw?pwd=v8fm 提取码: v8fm 
2、mac上有款大纲软件叫bike它可以实现深度链接，但是必要扩展名是bike，而不能是md（它可以打开markdown），否则它跟妙言一样也是浅层链接
真心希望能有一款深度链接的markdown编辑软件。这是hookmark的软件实现的，如果可以妙言支持，视频有时间戳（通过vlc），pdf有回链（skim），再来个markdown编辑软件，这是个闭环，但是就差个markdown编辑软件

**Comment by shoudeyunkaijianyueming** [comment]
所谓的深度链接就是不仅仅能回到该文件，而且能回到想回到的该文件标记处（一键链接）

**Comment by tw93** [comment]
我考虑了下，抱歉这个功能不是很好支持，同时应该不是公共能力功能，因为markdown下面这个技术实现也有难度，有兴趣可以给我提交代码看看
