### ISSUE TITLE
文档分享功能添加

### ISSUE THREAD

**Issue by Zjieke** [tw93/MiaoYan#284]
不知能否增加互联网分享功能，方便分享链接给朋友直接访问。

**Comment by tw93** [comment]
这一块会涉及到服务端计算资源，我想想怎么实现便宜些🤣

**Comment by Zjieke** [comment]
自己手动导出html+上传oss的方式，那每次有内容修改都得修改上传一次，

或者在产品本身就集成oss，用户自行配置相关accessKey信息，实现上传、分享。
1、可以默认都是本地编辑；
2、但点击分享按钮时，再将文件上传至oss，生成链接；
3、或者可以支持配置FTP、WebDav等服务，编写后的文件自动保存至对应目录，文件分享路径，我可以自己解决。

**Comment by tw93** [comment]
抱歉 这里我想了想还是有风险问题，当前还是更多考虑本地好了（国内安全政策会有些影响
