### ISSUE TITLE
每次编辑后，笔记列表都会重新排序（我选择的标题排序）

### ISSUE THREAD

**Issue by conanjunn** [tw93/MiaoYan#29]
0.5.0版本，每次编辑后，笔记列表都会按照修改时间排序，但我选择的是按标题排序。期望的结果是：编辑笔记后，笔记列表维持编辑前的排序不变。谢谢~

**Comment by tw93** [comment]
多点击一下按标题排序试试 相当于两个倒序逆序切换

**Comment by tw93** [comment]
已经支持，可菜单栏检查更新升级最新版本体验
https://github.com/tw93/MiaoYan/releases
