### ISSUE TITLE
Relative links don't work

### ISSUE THREAD

**Issue by matidio** [tw93/MiaoYan#290]
Relative links as described on github[^1] don't work.

Below an example reference/link[^2] to an example.pdf inside the current folder. A reference like this doesn't open referenced example.pdf inside the same folder as the source markdown file. Other examples that don't work below [^3][^4]

[^1]: [Github Flavor relative links](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links)
[^2]: (./example.pdf)
[^3]: (example2.pdf)
[^4]: (examplefolder/example3.pdf)

**Comment by tw93** [comment]
Maybe you can try this feature, Try it, maybe you can find a pattern.

<img width="345" alt="image" src="https://github.com/user-attachments/assets/87d783a5-a4cd-4810-a2c1-ab9edddeb313">

In addition, MiaoYan also supports the following relative document addresses, you can try
```
[[Title]]
```
