### ISSUE TITLE
Mojave 兼容性问题

### ISSUE THREAD

**Issue by Fujiwara-Chika** [tw93/MiaoYan#3]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/44722787/173186194-3376afb3-b2cc-493e-acc8-997b860b406d.png">
其一是 UI 显示
其二是切换到其它应用后，主界面消失

**Comment by tw93** [comment]
谢谢反馈，下个版本解决

**Comment by tw93** [comment]
@Fujiwara-Chika  https://qpluspicture.oss-cn-beijing.aliyuncs.com/gFwUyX/18.dmg
辛苦下载这个，然后试试兼容性问题看好了没

**Comment by Fujiwara-Chika** [comment]
> @Fujiwara-Chika https://qpluspicture.oss-cn-beijing.aliyuncs.com/gFwUyX/18.dmg
> 辛苦下载这个，然后试试兼容性问题看好了没

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/44722787/173730361-05390c25-137c-4045-8ff7-1783ddd12f15.png">
应该是修好了，感谢
