### ISSUE TITLE
重启mac后妙言笔记丢失

### ISSUE THREAD

**Issue by wonb168** [tw93/MiaoYan#302]
我妙言里的笔记保存在icloud下，新建了名changing的文件夹，里面有多个markdown文件，mac笔记本不关机使用正常，一旦关机重启后markdown笔记就丢失了，mac电脑上icloud下文件夹及文件都没了，妙言里也只显示一个空的changing目录，这是妙言的问题还是icloud的问题？

**Comment by tw93** [comment]
看起来是icloud的问题，看看是不是同步出问题了，包括看看网页版本的iCloud里面有没有记录

**Comment by tw93** [comment]
后面没有回复，先关闭，有问题，辛苦继续打开，或者在妙言朋友们的电报群里面加我私聊复现效果～
