### ISSUE TITLE
添加自动居中特性

### ISSUE THREAD

**Issue by DeShuiYu** [tw93/MiaoYan#304]
* 当使用![]()添加图片能否让图片自动居中
* 当使用块代码时候，能否让代码自动居中
* 当添加table，能够首行有颜色显示，并整个table自动居中
* 等等一系列居中，让文档更加美观

**Comment by tw93** [comment]
谢谢提供建议，其实我个人感觉自动居中没有那么好看，不过你可以通过去这个文件里面修改css，来自定义你的样式，提供了一个扩展的思路
<img width="619" alt="image" src="https://github.com/user-attachments/assets/d761344d-95fa-49e0-a655-a8f622d4ada4">
