### ISSUE TITLE
可以支持Checkbox吗

### ISSUE THREAD

**Issue by yinLiangDream** [tw93/MiaoYan#309]
谢谢作者提供了这么好用的工具，同时我提个诉求，可以将 <img width="71" alt="image" src="https://github.com/tw93/MiaoYan/assets/24502330/40f0c674-ac45-4ce2-96b9-cfdb54e5e832"> 渲染成
<img width="74" alt="image" src="https://github.com/tw93/MiaoYan/assets/24502330/2d4d582c-3aa4-43d2-87db-17bcee354d40">
格式吗

**Comment by tw93** [comment]
支持的，你试试我这个写法，甚至预览的时候还可以修改状态
```
- [x] dsad
- [x] dsad 
- [ ] adsdasd
```
