### ISSUE TITLE
更新最新版本之后闪退

### ISSUE THREAD

**Issue by lzcdev** [tw93/MiaoYan#312]
![4631703238437_ pic](https://github.com/tw93/MiaoYan/assets/16014249/545beb65-7d04-49ff-9b82-7c52649a25a1)

**Comment by tw93** [comment]
谢谢反馈，这个有复现路径吗？
我判断应该是 xcode 新版本我没有兼容到这个问题导致

**Comment by lzcdev** [comment]
复现方式就是点击更新妙言之后再打开就直接闪退了，然后尝试卸载重新下载仍然打不开。

我电脑系统是 macOs Big Sur 11.2.3，下载的妙言版本是1.14.1

**Comment by tw93** [comment]
请使用最新版本试试 1.15
