### ISSUE TITLE
编辑模式下，将「格式」中的放到编辑区域文本栏上方

### ISSUE THREAD

**Issue by chuangsheng** [tw93/MiaoYan#313]
编辑模式下，可以将[格式]中的放到编辑区域文本栏上方，这样就可以直接选中文字，然后点击「格式」中的操作了。类似于github的这个Issue的输入文本域（对于我这个markdown新手来说非常重要），嫌碍事的情况下也可以隐藏掉。

类似于下图：

<img width="905" alt="image" src="https://github.com/tw93/MiaoYan/assets/9959058/dceeb4e7-d1a5-42cf-aa96-0f4838fa05d6">

**Comment by tw93** [comment]
抱歉，这个功能我感觉对于喜欢简洁的用户太复杂了，很建议去记一下markdown的常用写法 https://www.markdown.xyz/basic-syntax/ 对你后面偏写文章相关工作会有很大帮助
