### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by uedkkk** [tw93/MiaoYan#314]
<img width="371" alt="image" src="https://github.com/tw93/MiaoYan/assets/61909421/034ddfe9-a572-4a10-8cac-a6cb3f060f42">
如图所示，当我想要把“Line3”用回车移到下一行时，就会闪退
原文如下：

```
- [ ] Line1
  - [ ] Line2Line3
```

**Comment by tw93** [comment]
谢谢反馈 有空我看看
