### ISSUE TITLE
Add smooth cursor animation?

### ISSUE THREAD

**Issue by spiljj** [tw93/MiaoYan#316]
Please consider adding cursor's animation like that in vscode(provided as an option), neovide or Microsoft Word(2013 and later). This feature is intended to enhance cursor visibility while typing, and also adds to aesthetics. I tried replicating that elegant nonlinear animation myself but ended up realizing it is beyond my capabilities.

Though this feature is not so widely discussed on the internet and  that this feature is sometimes controversial, I do hope someone could realize this feature in a md editor and, more hopefully, in Swift.

**Comment by tw93** [comment]
Thank you for your meticulousness. It took me a long time to discover this small detail.
However, considering that users will hardly notice this feature at the moment and it will take some time to implement in Swift, I plan not to do it for now.
