### ISSUE TITLE
软件有latex支持吗？如果没有，是否考虑支持？

### ISSUE THREAD

**Issue by EvanLuo42** [tw93/MiaoYan#32]

**Comment by tw93** [comment]
抱歉 暂时没有这个计划，因为这个软件主要是为markdown使用者产品化的

**Comment by EvanLuo42** [comment]
> @EvanLuo42 0.6.2 已支持 预计周末发布
> 
> ![image](https://user-images.githubusercontent.com/8736212/176200621-3ea5968a-bb2f-4539-a77e-8f3785f99615.png)

感谢
