### ISSUE TITLE
macbook M2文件夹不显示了

### ISSUE THREAD

**Issue by lisiyizu** [tw93/MiaoYan#322]
<img width="968" alt="image" src="https://github.com/tw93/MiaoYan/assets/12014252/823b317b-7d03-4823-8fbf-cd8493ada1bc">

**Comment by lisiyizu** [comment]
> 看看在iCloud里面有没有 或者在访达里面搜索一下文件 看看在哪儿

请问一下是不是有什么快捷键隐藏了文件夹，我重新下载了还是不行，导入不了文件夹。

**Comment by lx1229** [comment]
我也碰到了这种情况，之前的文件是基于

**Comment by lx1229** [comment]
软件用起来很舒服！为大神点赞！
我也碰到了这种情况，我之前使用miaoyan编辑的时候，是使用了以下的目录结构组织文件的：
一级目录 1
  - 二级目录 1.1
    - 文件1 
    - 文件2 
  - 二级目录 1.2
     - 文件1 
     - 文件2 
- 一级目录 2
    - 二级目录 1.1
    - 文件1 
    - 文件2 
  - 二级目录 1.2
     - 文件1 
     - 文件2 
但是有次软件打开目录就没了，没有找到其他的操作可以导入一级目录能够获取目录下文件的操作。

**Comment by lisiyizu** [comment]
> 软件用起来很舒服！为大神点赞！ 我也碰到了这种情况，我之前使用miaoyan编辑的时候，是使用了以下的目录结构组织文件的： 一级目录 1
> 
> * 二级目录 1.1
>   
>   * 文件1
>   * 文件2
> * 二级目录 1.2
>   
>   * 文件1
>   * 文件2
> 
> 但是有次软件打开目录就没了，没有找到其他的操作可以导入一级目录能够获取目录下文件的操作。

我就是你这种情况，突然有一天文件夹目录都没了，只剩下文件目录了。卸载重新安装都没用，导入不了目录

**Comment by houseme** [comment]
建议推出独立文件预览的方式就有了

**Comment by lisiyizu** [comment]
> 如果是选择单独打开过md文件，建议退出独立文件预览的方式就有了 其他情况就是调整图片里的2个隐藏显示就可以 ![image](https://private-user-images.githubusercontent.com/4829346/318371609-7470c1c7-2adf-42e3-a86a-bae966acbcb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDI5NjIsIm5iZiI6MTcxMjU0MjY2MiwicGF0aCI6Ii80ODI5MzQ2LzMxODM3MTYwOS03NDcwYzFjNy0yYWRmLTQyZTMtYTg2YS1iYWU5NjZhY2JjYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMDIxNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdhOTIyMDczYzYyMjJhYzZlZTMzN2EzMTAzZjEyZjc5ZTgyZjcyMWRkZGE0OTRiMWFhYjFhNmI4MDgzNGM0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5xltSPq99jyse6OvfMVzeQvQfqcqne3tSqp-qT2VElo)

试了没用，你的不是M2吧

**Comment by tw93** [comment]
应该是单独打开过文件导致，可以command+shift+W 关闭即可，或者 command+q强制退出即可

**Comment by lisiyizu** [comment]
> 应该是单独打开过文件导致，可以command+shift+W 关闭即可，或者 command+q强制退出即可

可以了，感谢大佬🙏
