### ISSUE TITLE
粘贴图片时，URL 错误

### ISSUE THREAD

**Issue by Hyseen** [tw93/MiaoYan#33]
![CleanShot 2022-06-20 at 09 25 41](https://user-images.githubusercontent.com/17402489/174509696-7727efdb-f486-4e03-b0e2-747a57d994e3.png)

如上图所示，粘贴剪贴板图片时会在同级目录下创建 `i` 目录，并将图片保存在该目录下。这时图片的 URL 应为 `i/xxx.png` 而非 `/i/xxx.png`。虽然在 MiaoYan 可以正常预览，但是用其它 Markdown 编辑器打开的时候无法正常预览图片

**Comment by tw93** [comment]
谢谢反馈，我下一个版本修正一下
