### ISSUE TITLE
更新1.15之后，空格有问题，标题不能正确识别了

### ISSUE THREAD

**Issue by houseme** [tw93/MiaoYan#330]
🙊辛苦提 bug 前，去找一下 [历史的](https://github.com/tw93/MiaoYan/issues?q=) 是否有提，同时检查一是否为最新版本。辛苦提供版本号、录屏或者截图、复现路径，期待解决的点这几个说明帮助我更好的解决问题。提交前请删除这些文字。<br>
🙊Look for [issue](https://github.com/tw93/MiaoYan/issues?q=) before you mention bugs Whether it is mentioned, and check whether it is the latest version. Need to provide the version number, screen capture or screenshot, reproduction path, and look forward to the points to be solved. These instructions help me better solve the problem. Please delete these words before submitting.

https://markdown.com.cn/editor/

<img width="1733" alt="image" src="https://github.com/tw93/MiaoYan/assets/4829346/cbd7ccd2-a521-45ff-a010-2800912bfe82">

这个是点击了 右上角的格式化，就出现不能正确识别 <h1-5>标签了。

@tw93

**Comment by houseme** [comment]
<img width="1439" alt="image" src="https://github.com/tw93/MiaoYan/assets/4829346/1955f6c9-c31b-45b8-93bd-cad5cedb6b7a">
这是妙言自己的预览

**Comment by tw93** [comment]
抱歉 我的锅，请更新到1.15.1，刚刚发布了，点击右上角菜单更新
