### ISSUE TITLE
新版本输入问题

### ISSUE THREAD

**Issue by ZyMousai** [tw93/MiaoYan#332]
MacBook Air
16g m1

新版本在输入标题的时候正常，输入正文的时候只能一个字一个字的输入。连打有问题，比如连打‘你好’，会直接显示‘你h a o’。

**Comment by ZyMousai** [comment]
系统是macos 14.5

**Comment by tw93** [comment]
看看是最新的1.15.1的版本吗？此外可以试试全局退出后再试试

**Comment by tw93** [comment]
试了试 直接升级到最新是ok的
