### ISSUE TITLE
文件内容消失

### ISSUE THREAD

**Issue by I-am-a-king-of-vue** [tw93/MiaoYan#335]
Mac 1.15.1版本 有一个已编辑的文件 然后新建一个没有任何内容的md 然后再删除 之前文件编辑的内容消失

**Comment by tw93** [comment]
可以去原有文件夹里面看看，看一下设置存储位置

**Comment by I-am-a-king-of-vue** [comment]
一堆脏话无力吐槽 
写了很久的笔记没了
具体步骤
打开笔记 
搜索内容
搜索到0条
返回笔记
内容清空
不确定是否百分百复现 但是概率很高 之前已经被删了3 4次了
原文件夹看了也没有内容
累了 卸载了
