### ISSUE TITLE
全文搜索后继续编辑，搜索匹配到的内容不可读

### ISSUE THREAD

**Issue by yansq** [tw93/MiaoYan#341]
## 版本号

1.15.1

## 复现方式

创建一个名为"test doc"的文件
<img width="943" alt="image" src="https://github.com/tw93/MiaoYan/assets/26108404/4e8bd4ac-c75c-48aa-ba54-f16804d3569a">

在搜索框中搜索 "test"
<img width="935" alt="image" src="https://github.com/tw93/MiaoYan/assets/26108404/19f15814-9e98-49e7-b25f-bcc89463f7e7">

将光标置于 “test doc”文件中的最后一行末尾，然后点击回车：
<img width="946" alt="image" src="https://github.com/tw93/MiaoYan/assets/26108404/7c88d794-3d90-4cfe-b7ea-8af255088bec">
匹配到的文字变为白色

**Comment by tw93** [comment]
感谢反馈，我下一个版本来修复一下，的确是Bug了

**Comment by tw93** [comment]
已经更新，最近几天发布一个版本，请关注发布日志～
