### ISSUE TITLE
需要支持Mermaid或者PlantUML语法，目前没看到如何添加？并且代码高亮也不知道如何指定语法，例如sql，sheel、java、go

### ISSUE THREAD

**Issue by hellohushuai** [tw93/MiaoYan#342]
需要支持Mermaid或者PlantUML语法，目前没看到如何添加？并且代码高亮也不知道如何指定语法，例如sql，sheel、java、go

**Comment by tw93** [comment]
大部分是保持 Github 的使用习惯。
1. Mermaid 使用可见  https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
2. 关于 sql，sheel、java、go 使用语法这里使用的是 https://highlightjs.org/demo ，更多使用可以参考 https://www.markdownguide.org/extended-syntax/#syntax-highlighting
