### ISSUE TITLE
希望能加上对单行文本的部分字体修改颜色的功能

### ISSUE THREAD

**Issue by markyun** [tw93/MiaoYan#345]
🏂 很感谢你的妙言 app， 希望能加上对单行文本的部分字体修改颜色的功能。

如图：
<img width="780" alt="image" src="https://github.com/user-attachments/assets/de365ccb-1dc7-4a3f-85c1-f62c44580dd5">

**Comment by tw93** [comment]
更感谢你的建议，当前对于编辑模式应该不会支持非语法展示外的颜色，不过假如你是想预览的时候展示这个颜色，是支持的。
可以试试类html标签写法
```
 <span style="color:red">超链接</span>
```
