### ISSUE TITLE
输入某种格式的代码 app 会直接崩溃

### ISSUE THREAD

**Issue by mancuoj** [tw93/MiaoYan#349]
https://github.com/user-attachments/assets/dc464bd9-70b2-4ca2-af21-99141c67be05

如视频所示，输入回车后直接崩溃，app 版本最新版本

**Comment by tw93** [comment]
谢谢反馈 我来看看

**Comment by Yak0xff** [comment]
> 谢谢反馈 我来看看

这个问题这边发现是字体加载的问题，有空看下是否可合入。https://github.com/tw93/MiaoYan/pull/351
