### ISSUE TITLE
有没有考虑增加双击程序最上部分将其界面最大化的功能呢

### ISSUE THREAD

**Issue by sbccznfy** [tw93/MiaoYan#35]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/72488394/174604246-703d9d82-331b-4f64-b78b-58cf1b5603de.png">
可不可以增加一个功能，像其他的应用一样，双击左上方空白位置，然后将程序的界面拓展到整个界面呢，效果如图
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/72488394/174604600-9e920441-ba5b-469a-8099-fda61b5d2218.png">

**Comment by tw93** [comment]
我看大部分软件都是双击标题栏直接最小化了，你说的是哪一个软件，我去看看

超级推荐使用这个软件
https://rectangleapp.com/

**Comment by tw93** [comment]
已经支持，可菜单栏检查更新升级最新版本体验
https://github.com/tw93/MiaoYan/releases

**Comment by sbccznfy** [comment]
好的，看到效果啦，感谢🎉
