### ISSUE TITLE
导出渲染时，能否支持不同字体？

### ISSUE THREAD

**Issue by yo1995** [tw93/MiaoYan#350]
能不能像html里面的`font-family:`一样，指定多个字体，这样在渲染中英文混合的文本时能够自动使用不同的字体渲染？

可以指定西文字体在前，中文字体在后，这样就能渲染得更加合适。

抱歉没有花时间去读代码，或许这个功能不好实现，如果是这样可以直接close issue as not planned

**Comment by tw93** [comment]
其实好做，可以根据当前妙言支持的3个字体写一个枚举兼容，你可以列一列，我来加也行，你来pr也可以

**Comment by tw93** [comment]
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/f7c1570d-5f7a-4f8a-b5b8-38c667c01d24">
其实现在就是这样，不过这里的导出最终原理其实是渲染一个html的方式

**Comment by yo1995** [comment]
谢谢，昨天验证了确实现在就是这样，赞 👍
