### ISSUE TITLE
希望增加marmaid代码失败、显示功能

### ISSUE THREAD

**Issue by Xinghanzzy** [tw93/MiaoYan#357]
希望增加流程图代码，marmaid的支持

**Comment by tw93** [comment]
支持的，参考 https://github.blog/developer-skills/github/include-diagrams-markdown-files-mermaid/
很多地方会和github readme里面支持的语法一致，你去试试，比如
<pre>
```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```
</pre>
