### ISSUE TITLE
在表格中出现字体颜色显示异常

### ISSUE THREAD

**Issue by sbccznfy** [tw93/MiaoYan#38]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/72488394/174831442-0bb2a61b-f7ce-4a57-8768-f5f90234de59.png">
源代码如上图，实际显示如下图
<img width="478" alt="image" src="https://user-images.githubusercontent.com/72488394/174831666-dc5d1451-835b-4bf3-bcac-bc7506f73202.png">

**Comment by tw93** [comment]
谢谢反馈 近期版本我修复一下

**Comment by tw93** [comment]
本地版本已经修复，近期会发布，辛苦关注release
