### ISSUE TITLE
[ FEATURE ]: 是否可以加入使用本地字体

### ISSUE THREAD

**Issue by keyding** [tw93/MiaoYan#42]
可以加入使用本地字体的配置选项。

**Comment by tw93** [comment]
暂时不支持，你可以把你觉得不错的字体给我，我加进去给大家使用

**Comment by keyding** [comment]
[jf open 粉圆](https://github.com/justfont/open-huninn-font)，不过中文的话，繁体支持的比较好，简体中文部分字可能不支持。

**Comment by tw93** [comment]
@keyding 看了下这个字体，7.6m的样子，加入进去对妙言而言有些大，支持自定义字体我记录一下，后面等编辑器基本功能优化完成以后，可以想想产品上如何实现

**Comment by EvanLuo42** [comment]
[SF Pro](https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg)

macOS上一直看的这个字体，别的有点不太习惯，如果可以的话可以帮忙加下吗谢谢。
