### ISSUE TITLE
超长链接内容不能自动强制换行

### ISSUE THREAD

**Issue by jonnywang** [tw93/MiaoYan#44]
实际内容

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/960982/174953036-b298de5e-1eac-4005-bb2d-35765b342f3a.png">

预览效果
<img width="339" alt="image" src="https://user-images.githubusercontent.com/960982/174952781-918b6c72-7da8-48fd-ad9c-16f8b28103de.png">

**Comment by tw93** [comment]
谢谢反馈，最近一次要发布的版本已修复，待最近发布~
