### ISSUE TITLE
编辑器窗口顶部能不能保留标题栏， 这样可以点击拖动，双击放大

### ISSUE THREAD

**Issue by jonnywang** [tw93/MiaoYan#46]
编辑器窗口顶部能不能保留标题栏， 这样可以点击拖动，双击放大

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/960982/174999470-b8ecb2c2-a160-46d2-a1b6-2992c31d88a8.png">

**Comment by tw93** [comment]
现在也可以，升级到最新版本
然后这个位置和你标注的地方更上面一些都是可以的
![image](https://user-images.githubusercontent.com/8736212/175001365-c97d5a4f-ac68-4463-b4bd-17a4f26c157a.png)

**Comment by jonnywang** [comment]
顶栏太小，实在不好操作定位
