### ISSUE TITLE
[Feature]是否支持字数统计？

### ISSUE THREAD

**Issue by tsurumi-yizhou** [tw93/MiaoYan#47]
有用其写文章的需求。
是否有支持字数统计？
如果有，那么开关在哪里？
如果没有，可否支持下？实现上技术难度应该不大。

**Comment by tw93** [comment]
当前没有，字数统计主要场景是什么？

**Comment by tsurumi-yizhou** [comment]
> 当前没有，字数统计主要场景是什么？

看自己写了多少字……

**Comment by tw93** [comment]
后面支持下，放到文档信息这个功能里面去，当前优先优化编辑体验
