### ISSUE TITLE
任务列表预览样式建议

### ISSUE THREAD

**Issue by Hyseen** [tw93/MiaoYan#49]
任务列表在预览时，复选框前面会多出来无序列表的圆点符号

```
- [x] item1
- [ ] item2
- [ ] item3
```

上面的任务列表在预览和导出时会被渲染成如下样式：
![image](https://user-images.githubusercontent.com/17402489/175238868-9bc4ee5f-2d77-48ea-b9a1-a26035daf999.png)

希望可以调整一下，去掉前面的圆点

**Comment by tw93** [comment]
最近版本已经修复 等发布～

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/releases/tag/V0.6.1
