### ISSUE TITLE
请问支持类似Quiver的同时显示预览和编辑界面吗？

### ISSUE THREAD

**Issue by liweijian** [tw93/MiaoYan#50]
以及是否支持设置图片大小？即类似Quiver 语法: `![IMAGE](quiver-image-url/DFCF457DF8D064D1943F96ACD33D17FB.jpg =600x)`

<img width="800" alt="image" src="https://user-images.githubusercontent.com/19320783/175444310-36f361ed-53a9-40e7-ab31-c70b8b2af668.png">

**Comment by tw93** [comment]
双栏有这个计划
图片那个其实我比较习惯 img 标签方式会更加好兼容些

**Comment by tw93** [comment]
先关闭，这个功能会放到编辑器体验优化完成以后做
