### ISSUE TITLE
新建文稿时候光标是否能自动聚焦到重命名状态

### ISSUE THREAD

**Issue by jonnywang** [tw93/MiaoYan#51]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/960982/175492758-ed6f3477-be2e-4003-8bf4-e78efe203ecc.png">

--------------
- [ ] 新建文稿时候光标是否能自动聚焦到重命名状态
- [ ]  文稿列表是否可以自设颜色区分
- [ ] 文稿是否可以自设符号标记

如图， 非常棒的软件，希望越做越好

**Comment by tw93** [comment]
谢谢你的建议，都很不错，慢慢支持
1. 新建文稿时候光标是否能自动聚焦到重命名状态  这一块我优化了很久，这个版本ok了，等完善发布
2. 2、3 这一块后面我想办法

**Comment by tw93** [comment]
文稿列表是否可以自设颜色区分 和  文稿是否可以自设符号标记  这两个是不是重复了功能上，有对应的案例吗

**Comment by tw93** [comment]
好的，这个先关闭
刚刚发布了0.6.1版本，去升级看看https://github.com/tw93/MiaoYan/releases/tag/V0.6.1
