### ISSUE TITLE
预览速度有点慢

### ISSUE THREAD

**Issue by zwmmm** [tw93/MiaoYan#53]
不知道是否和网络有关系，预览速度极慢，且没有 `loading` 效果 还以为出 `bug` 了

**Comment by tw93** [comment]
贴一下Markdown文件
是不是有cdn图片？

**Comment by zwmmm** [comment]
用的就是默认的介绍妙言

**Comment by tw93** [comment]
那我知道了，里面有一个gif的视频，可能是他影响的，你直接试试自己写的那种
