### ISSUE TITLE
需求：期望图片等富媒体支持在md文件内base64编码

### ISSUE THREAD

**Issue by litaooo** [tw93/MiaoYan#55]
理由：
1. 图片会存在冗余或导致md文件出错。
个人文件积累多了后，在图片文件夹中，根本不知道某个图片被哪些文件引用了。如果某个md文件中需要修改一张图片，可能会导致其他md文件出错。如果图片新版本取新文件名，长期积累下来会导致图片文件夹有不少冗余图片。
2. 难于分享。
如果想分享md文件，显然单独存储的图片等富媒体很难被同时打包出来一起分享。
3. 难于管理。
长期使用下来，必然存在md文件移入各种不同深层次目录中，图片等很难同时移动。

**Comment by tw93** [comment]
可是base64编码会变长3倍多，很影响展示和使用
其实正解是可以去搞一个阿里云的oss+upic的方式来弄，变成链接保存才是比较好的，你觉得呢？
