### ISSUE TITLE
自动生成 文件名 + 时间 的文本

### ISSUE THREAD

**Issue by geekgogo** [tw93/MiaoYan#57]
每次通过右键打开都会生成【文件名 + 详细时间】的文本
<img width="974" alt="截屏2022-06-26 19 47 35" src="https://user-images.githubusercontent.com/23014680/175812732-b63081f7-5772-4904-8460-9db541643a29.png">

**Comment by tw93** [comment]
谢谢反馈 这是一个“正确”的代码逻辑，其实不对，下一个版本支持文件右键单独打开的模式

**Comment by tw93** [comment]
先关闭，在实现中了，完毕后回复此issue
