### ISSUE TITLE
希望支持LaTex排版和图床功能

### ISSUE THREAD

**Issue by fanpeizhou** [tw93/MiaoYan#62]
UI非常漂亮的一款app，可惜目前好像不支持LaTex？插入图片是上传到iCloud上，自用完美。但是如果是分享给别人，恐怕是访问不了图片，希望能支持类似UPic的图床。

**Comment by fanpeizhou** [comment]
> > UI非常漂亮的一款app，可惜目前好像不支持LaTex？插入图片是上传到iCloud上，自用完美。但是如果是分享给别人，恐怕是访问不了图片，希望能支持类似UPic的图床。
> 
> #32 这条议题说了，LaTeX应该是不支持的 #26 这条议题提到了，图床应该会在以后支持

好的，谢谢。以后我先看closed里的再提交issue😂

**Comment by tw93** [comment]
先关闭，楼上回复正确
支持LaTeX这一块可以一起再讨论讨论，方便说说好处吗？

**Comment by fanpeizhou** [comment]
> 先关闭，楼上回复正确
> 支持LaTeX这一块可以一起再讨论讨论，方便说说好处吗？

理工科记东西还是需要些公式啥的。比如没有LaTeX语法支持的话，就是x^2+y^2=1，巨丑，还是各种上下标积分号啥的，根本就无法输入，能输入的单从美观方面来说也接受不了。当然也十分理解作者个人精力有限，要是愿意做的话，本人十分乐意等。

**Comment by tw93** [comment]
我get到了，也即支持数学公式类的展示，而非支持LaTeX论文排版那么全的吧？
那我可以试试看怎么支持，我打开这个issue，辛苦关注，这个周末我去试试看

**Comment by fanpeizhou** [comment]
>

**Comment by tw93** [comment]
@fanpeizhou done 0.6.2版本，预计这周6左右发布

![image](https://user-images.githubusercontent.com/8736212/176200056-1365f36e-affd-422c-8862-068bfd53c632.png)

**Comment by fanpeizhou** [comment]
> @fanpeizhou done 0.6.2版本，预计这周6左右发布
> 
> ![image](https://user-images.githubusercontent.com/8736212/176200056-1365f36e-affd-422c-8862-068bfd53c632.png)
> 
> 同时假如有兴趣，可以帮忙在你们学校推荐妙言给更多志同道合的同学使用，哈哈

好快啊！😰，会的会的，好东西要分享。

**Comment by tw93** [comment]
@fanpeizhou  更新到最新版本试试，记得在设置中开启一下~

**Comment by tw93** [comment]
@fanpeizhou @shellRaining @JounQin 图床已经OK
https://github.com/tw93/MiaoYan/releases/tag/V0.7.0
