### ISSUE TITLE
光标在标题栏时，点击文件侧边栏的本文件图标无法聚焦

### ISSUE THREAD

**Issue by sbccznfy** [tw93/MiaoYan#64]
如图，此时我的光标在标题栏
<img width="491" alt="image" src="https://user-images.githubusercontent.com/72488394/175945155-d814e87d-7064-4095-9cdd-37bf01c81fa6.png">
点击左侧的测试2按钮，看到光标仅会跳转到正文部分
<img width="522" alt="image" src="https://user-images.githubusercontent.com/72488394/175945289-fd0c11c0-62c3-4634-95cc-1ca472a8977a.png">
如果点击其他文件按钮，可以看到光标从正文部分一闪而过，然后立即跳到对应文件中去

不知道这是否是一个特性呢，我在点击后想要应用快捷键command+backspace删除文件，但是却没有达到预期效果

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/releases/tag/V0.6.2
