### ISSUE TITLE
macos 10.15版本下，显示效果问题

### ISSUE THREAD

**Issue by admover** [tw93/MiaoYan#68]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/8574628/176574314-937841ed-bdca-44c2-a0a6-2056e699eaed.png">

一个小问题，老版的macos上，选中状态，灰色部分与搜索框太近，效果不是很好。

**Comment by tw93** [comment]
😂 其实妙言不支持10.15版本下的系统了，建议升级一个版本到去年的那个系统会好不少

**Comment by admover** [comment]
MacBook Pro (Retina, 15-inch, Early 2013)
好吧，已经不让升级了😓
