### ISSUE TITLE
链接颜色异常

### ISSUE THREAD

**Issue by sbccznfy** [tw93/MiaoYan#69]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/72488394/176713712-8337a3e1-3088-4e90-bc2d-3e46ac198833.png">

单独显示英文链接，颜色正常为绿色，但是如果夹杂一些中文，那么英文将不会显色

<img width="279" alt="image" src="https://user-images.githubusercontent.com/72488394/176714067-1d40f53a-e192-4d75-bea2-46bfe9f9e8cd.png">

**Comment by tw93** [comment]
已经解决，下一个版本给发了

**Comment by tw93** [comment]
0.7.0 ok https://github.com/tw93/MiaoYan/releases/tag/V0.7.0
