### ISSUE TITLE
[bug?] 预览状态下，文章标题可修改

### ISSUE THREAD

**Issue by QuentinHsu** [tw93/MiaoYan#7]
如题，预览状态下，文章内容不可修改，但文章标题却可修改。

![image](https://user-images.githubusercontent.com/21162238/173212834-b47e8c9c-5e11-42ff-9868-082d136709c6.png)

我认为这个 bug。

不过有待作者你的功能设计反馈。

**Comment by tw93** [comment]
是bug 我这个版本改一波，谢谢反馈

**Comment by tw93** [comment]
0.3.3 版本已经修复，今天发布更新
