### ISSUE TITLE
希望优化一下有序列表从中间插入的过程

### ISSUE THREAD

**Issue by shellRaining** [tw93/MiaoYan#70]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/72488394/176714526-d7f49eec-0e8d-42b2-bec6-ead8bdf9b548.png">

如图，光标在第一项最后，若此时按下回车，会发现后面的序号不会依次递增，造成排版的麻烦。GitHub这个功能是没有问题的，希望大佬加一下😁

<img width="913" alt="image" src="https://user-images.githubusercontent.com/72488394/176714795-46e654ff-e980-45ca-b9d0-469fa23d6809.png">

（emmm，但是似乎，这个对预览效果是不会有影响的）

<img width="311" alt="image" src="https://user-images.githubusercontent.com/72488394/176715586-6b172da0-6b0b-432b-bc8c-b09bcbf75f0e.png">

**Comment by tw93** [comment]
这个我想想实现哈，看了下不少 markdown 都有这个问题，看看怎么解决

**Comment by tw93** [comment]
不太影响使用，先hold下好啦
