### ISSUE TITLE
同一版本 GitHub release sha256 会变化？

### ISSUE THREAD

**Issue by JounQin** [tw93/MiaoYan#72]
See also https://github.com/Homebrew/homebrew-cask/pull/127000

**Comment by tw93** [comment]
哈哈哈 忽略 上次发完以后修了一个小bug 导致，不想版本太多干扰用户不停升级

**Comment by JounQin** [comment]
这样也挺干扰😹

**Comment by tw93** [comment]
哈哈 下次尽量不这样
