### ISSUE TITLE
[Feature]能否支持内部笔记间的跳转链接

### ISSUE THREAD

**Issue by dxxxp** [tw93/MiaoYan#75]
比如笔记A引用了笔记B，能否支持添加一个跳转链接，点击后打开笔记B。
试过 ./B.md 这种相对路径的链接方式，不生效

**Comment by tw93** [comment]
这个我想想实现，赞挺好的想法

**Comment by tw93** [comment]
实现好啦 用[[标题名]] 这样标识内部跳转链接，预计下周3前会发一个版本

**Comment by dxxxp** [comment]
赞赞赞 好快啊 多谢多谢

**Comment by tw93** [comment]
https://github.com/tw93/MiaoYan/releases/tag/V0.8.0  已经发布
@dxxxp
