### ISSUE TITLE
关于格式化及高亮显示的小问题

### ISSUE THREAD

**Issue by Zilanlann** [tw93/MiaoYan#76]
## 第一个是关于格式化
这个功能很好用，但是目前遇到的问题是连代码块中的内容也会一起格式化.
个人感觉代码块中的内容应该大部分时候不需要格式化，所以希望默认格式化能避开代码块。
## 第二个是一个小bug，如下，高亮显示有问题
<img src="https://picgo-1307397181.cos.ap-shanghai.myqcloud.com/uPic/202207070947J8uFzv.gif">

**Comment by tw93** [comment]
感觉反馈产品体验细节！近期修复优化
