### ISSUE TITLE
关于操作上的优化建议

### ISSUE THREAD

**Issue by LanYunDev** [tw93/MiaoYan#77]
command + Z 支持撤回文件类型的操作.例如复制了一个文件可以撤回,或者删除了一个文件,然后撤回
ESC 支持更多操作,比如搜索,重命名等操作能通过按ESC打断而不是点击
切换到预览模式以及自动排版操作等,支持不滚动到最上方开始
其他建议日后补充,(因为刚上手一分钟)
软件很漂亮,做得很好,
但我个人有一些偏好,希望能考虑考虑
所见所得模式,挺不错的,如果可以做就挺好
插入照片支持本地
<img width="492" alt="image" src="https://user-images.githubusercontent.com/95263282/177741195-140913ba-9a80-4bfe-bcdb-9077d91b9e19.png">
一些主题.
当然,目前软件已经非常不错了👍

**Comment by tw93** [comment]
赞赞赞 好建议 我会放到todo里面去

**Comment by arashicage** [comment]
可不可以加一个功能：通过快捷键，按钮支持通过外部 app 进行编辑

**Comment by tw93** [comment]
@arashicage  抱歉 这个没有考虑，可以通过 command + i 打开，然后选择，我是想讲miaoyan当做默认的markdown编辑器

**Comment by tw93** [comment]
这几个基本上已经支持到位，删除文件支持撤回、ESC 支持更多操作、ESC 支持更多操作
其他的后面我想到比较好的产品实现再来弄

**Comment by LanYunDev** [comment]
好的~感谢开发者!

**Comment by tw93** [comment]
@LanYunDev https://github.com/tw93/MiaoYan/releases/tag/V0.8.0
