### ISSUE TITLE
文章标题带有目录分隔符时文档不会在列表里列出来

### ISSUE THREAD

**Issue by arashicage** [tw93/MiaoYan#78]
文章标题带有目录分隔符时文档不会在列表里列出来，如果能支持创建多级目录就更棒了
<img width="799" alt="image" src="https://user-images.githubusercontent.com/5427687/177813339-37a0768f-6b09-4ef3-9a90-f2cf882e3489.png">

**Comment by tw93** [comment]
抱歉 标题不支持为这种形式，因为会被识别成路径，也不便于后续查找和管理，因为最终是源文件的名称~
多级目录我在想怎么产品表达会好一些，后面看
