### ISSUE TITLE
代码块没有语法提示，且输入的时候不高亮，效率有点低

### ISSUE THREAD

**Issue by zwmmm** [tw93/MiaoYan#79]
现在只能在编辑器上吧代码快写好 在复制过来，希望作者能支持下这个功能

**Comment by Zilanlann** [comment]
难道不应该就是复制过来吗，连typora都不适合直接在里面写代码吧

**Comment by zwmmm** [comment]
> 难道不应该就是复制过来吗，个人认为单纯的markdown编辑器不需要编写代码的功能

写代码很常见，就和图片一样，那你也可以用其他工具提前上传好，但是编辑器内置体验会更佳

**Comment by qsjc** [comment]
....编辑器内代码块有提示功能这个需求有点过头了吧0.0

**Comment by tw93** [comment]
> ....编辑器内代码块有提示功能这个需求有点过头了吧0.0

哈哈 是的 假如有轻量的可以试试 不过有些悬 先关闭

**Comment by tw93** [comment]
@zwmmm 不是特别好实现，有没有轻量办法
