### ISSUE TITLE
程序窗口无法保持后台运行

### ISSUE THREAD

**Issue by ievnkai** [tw93/MiaoYan#8]
移到其他应用程序后，程序窗口丢失，需要点击 Dock栏才能重新唤起程序的窗口，或者通过任务切换器也可以唤起程序窗口。

这应该是一个 BUG。至少很影响体验。

**Comment by tw93** [comment]
辛苦反馈，这个版本马上修复

**Comment by tw93** [comment]
0.3.2已经修复，可以在妙言菜单栏检查更新里面更新到最新的版本
