### ISSUE TITLE
窗口顶部空间有点小不便于鼠标拽托

### ISSUE THREAD

**Issue by ChaoqunCHEN** [tw93/MiaoYan#82]
由于个人习惯原因需要经常调整窗口的位置, 然而现在这个版本窗口顶部可用于鼠标点击拽托的空间有限. 我的第一反应是点击文档标题, 但是点击后变成了修改标题. 也许可以考虑把标题修改变成点击修改键后进入修改模式, 或者把整个窗口的顶部空间变大一点. 谢谢.

**Comment by tw93** [comment]
安排 我想想产品实现

**Comment by tw93** [comment]
@ChaoqunCHEN 
试试拖动这个位置看能否解决你的习惯哦
![image](https://user-images.githubusercontent.com/8736212/178393825-78a682eb-99c8-47ec-a9bf-f4f3ff3877ea.png)

**Comment by tw93** [comment]
暂时没有回复，等到有需要直接重启即可

**Comment by ChaoqunCHEN** [comment]
可以的, 谢谢!
