### ISSUE TITLE
Markdown 高亮的小 bug

### ISSUE THREAD

**Issue by sptuan** [tw93/MiaoYan#83]
当短代码渲染中，如果带有 https 链接，可能会导致后续短代码结束后，高亮颜色不正确。

version:
v0.8.0

示例文本：
```
取当前 Unix 时间戳为 `timestamp`, 签名秘钥为 `key`，计算签名方式为 `md5(key+path+timestamp)`

例如用户原始访问的 URL 为 `https://example.com/1/test.jpg?foo=bar`，当前时间为 `1657725452`，key 为 `ba0620aa845a89ce4e11f88a42c23778`
```

实际效果
<img width="752" alt="image" src="https://user-images.githubusercontent.com/17442205/178770390-0358b902-c4c5-43c0-a930-606844535c92.png">

PS:感谢开发这款 Markdown 笔记软件！很喜欢

**Comment by tw93** [comment]
谢谢反馈 最近版本刚好在做语法高亮这一块优化，会给加上～

**Comment by tw93** [comment]
0.9.0 已发布，支持了这个，可去更新~
https://github.com/tw93/MiaoYan/releases
