### ISSUE TITLE
我挺喜欢这个风格的，但是想问怎么给文件添加目录呢

### ISSUE THREAD

**Issue by CurryKobe** [tw93/MiaoYan#85]

**Comment by tw93** [comment]
点击第一栏左上角 + 按钮试试，或者是直接 进入到对应的妙言文件夹新增目录，可以理解成和管理你本地文件是一模一样的

**Comment by CurryKobe** [comment]
不是，我说的是md文件里面的目录，内容目录

**Comment by tw93** [comment]
@CurryKobe 😂 还是没有听懂 方便举一个例子吗

**Comment by CurryKobe** [comment]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/32093993/178954701-f38aeae1-8f8a-4ceb-b076-ea11c961a143.png">
这个这个，看图

**Comment by CurryKobe** [comment]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/32093993/178954863-77d82abd-21d8-4c12-af98-0cf713d06a22.png">
就是这个嘛，内容的目录

**Comment by CurryKobe** [comment]
github不是用[toc]就可以了么

**Comment by tw93** [comment]
哦哦 懂啦懂啦 当前妙言不支持 我看看GitHub的效果 这个用途你主要用在哪些场景哦

**Comment by CurryKobe** [comment]
就是想插入个目录而已啦🐶

**Comment by tw93** [comment]
下一个版本会上一个支持锚点滚动的功能，toc这一块你可以自定义自己写即可
这样使用
```
[标题名称1](#标题名称1)
[标题名称2](#标题名称2)

# 标题名称1
## 标题名称2
```
