### ISSUE TITLE
是否考虑实验性支持block protocol？

### ISSUE THREAD

**Issue by sluke** [tw93/MiaoYan#86]
https://blockprotocol.org/docs

![image](https://user-images.githubusercontent.com/97678/151566810-f1e6be74-a48c-431a-8bfe-cbf600500c06.png)

**Comment by sluke** [comment]
> 有具体的应用或者网站支持这个吗我去玩玩 在即将发布的这个版本支持了hash锚点不知满足使用不

notion 算是吧，这是一个很“重”的需求，会让软件向着复杂发展，失去markdown的简洁，慎重

**Comment by tw93** [comment]
暂时妙言会优先简洁易用漂亮为第一优先级，确保我们工程师写文档的体验最舒服
