### ISSUE TITLE
7.15号打包的版本bug

### ISSUE THREAD

**Issue by Macrohoo** [tw93/MiaoYan#87]
1、文件夹下新建一个md的时候，有机率触发程序整个崩溃
2、编辑再修改，点击back清除某个内容的时候，编辑可视区域乱跳。

![image](https://user-images.githubusercontent.com/15125523/179335637-ed559731-a8ec-4a0f-a18a-9b9758950757.png)

**Comment by tw93** [comment]
我这边比较难复现，方便录制一个视频吗？

**Comment by Macrohoo** [comment]
已发你邮箱

**Comment by tw93** [comment]
感谢感谢，已经修复，辛苦直接打开妙言菜单栏检查更新，更新到0.9.2版本即可
