### ISSUE TITLE
预览

### ISSUE THREAD

**Issue by ailee945** [tw93/MiaoYan#88]
1. 源码切换到预览后，是从文档开头预览，不是从编辑的位置预览；
2. 行内的代码块样式能否增加背景，类似于github的行内代码块；

**Comment by tw93** [comment]
谢谢反馈，这两个功能我下一个版本给加上

**Comment by tw93** [comment]
1. 行内的代码块样式能否增加背景，类似于github的行内代码块；
这个可以在 0.9.2版本已经更新上

---

1 这个由于是两个容器，看着简单，不过还没有想到好办法，我先记下，先关掉这个issue

**Comment by tw93** [comment]
已经支持，预计本周发布

**Comment by tw93** [comment]
已发布，可去更新
