### ISSUE TITLE
【功能建议】为代码块增设单独的字体选择

### ISSUE THREAD

**Issue by schrodingercatss** [tw93/MiaoYan#89]
目前的字体选择只能是整体选择，而部分字体是非等宽字体，在使用代码块时阅览不够方便，希望能单独增加一栏给代码块选择字体的选项。

**Comment by tw93** [comment]
谢谢反馈，想了想，的确有必要，这个我放1.0版本

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/179998318-edafb34f-f74f-4638-abdd-19b328a742f7.png)
代码已经支持，放到1.0版本发布，预计周五前发一个版本

**Comment by tw93** [comment]
已发布，可去更新
