### ISSUE TITLE
有一些显示bug

### ISSUE THREAD

**Issue by HeyManMan** [tw93/MiaoYan#9]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/18532708/173220761-c38fcacc-a312-42ba-aff7-e9d10a603c26.png">

系统：10.15.7 
版本：0.3.1

**Comment by tw93** [comment]
谢谢反馈，最近一个版本我修复下

**Comment by tw93** [comment]
@HeyManMan https://qpluspicture.oss-cn-beijing.aliyuncs.com/gFwUyX/18.dmg
辛苦下载这个，然后试试兼容性问题看好了没
