### ISSUE TITLE
请问Mac上支持打开任意目录么？

### ISSUE THREAD

**Issue by vipzhicheng** [tw93/MiaoYan#90]
我看只能在默认的目录编辑，菜单栏里没有找到打开目录的选项。

**Comment by tw93** [comment]
command + o 试试，最新版本有一个单独编辑的模式
![image](https://user-images.githubusercontent.com/8736212/179437167-4af9d51c-6080-48c8-b7be-0638b392bffa.png)

**Comment by vipzhicheng** [comment]
还不太行，好像显示不出目录

**Comment by tw93** [comment]
录制一个视频看看

**Comment by vipzhicheng** [comment]
![screencast](https://user-images.githubusercontent.com/1209538/179885337-5b554fe7-7a2d-48a8-b3da-c034c084f19f.gif)

v0.9.2

**Comment by vipzhicheng** [comment]
这个目录导航不知道是什么原理，我打开一个之前的markdown目录，看到的不是资源管理器那样的树形结构，貌似各个层级的都拉平了。

<img width="201" alt="image" src="https://user-images.githubusercontent.com/1209538/180133202-fdbb515c-3dc0-4137-8ede-3fad27b0b44d.png">

**Comment by saup007** [comment]
> 这个目录导航不知道是什么原理，我打开一个之前的markdown目录，看到的不是资源管理器那样的树形结构，貌似各个层级的都拉平了。
> 
> <img alt="image" width="201" src="https://user-images.githubusercontent.com/1209538/180133202-fdbb515c-3dc0-4137-8ede-3fad27b0b44d.png">

貌似还不支持多级目录，我的也这样显示，一个层级。
