### ISSUE TITLE
换行和多行的行间公式

### ISSUE THREAD

**Issue by tksze** [tw93/MiaoYan#93]
1. **换行**
目前的 line break 是，源码换新一行，渲染也换新一行。而在 github (issue 除外) 和 vscode 里，源码里换行也渲染成同一段。
只有空两格再换行才是真换行。
例如：
```
第一句。
第二句。
```
渲染出来为：
```第一句。第二句。```
而软换行为：
```
第一句。  |<----（空两格）
第二句。
```
渲染出来为：
```
第一句。
第二句。
```
参考 [linebreak](https://gist.github.com/shaunlebron/746476e6e7a4d698b373)。在 marktext 那边，说是与 formatting 功能冲突所以才不这样换行。不过他们是 WYSIWYG，而 miaoyan 不是，不知道会不会也有这个问题。

2. **多行的行间公式**
行间公式跨行则不渲染，如：
```
$$
D=\left[ \begin{matrix}
 1&0&0\\
 0&-2&0\\
 0&0&-2
 \end{matrix} \right]
$$
```

$$
D=\left[ \begin{matrix}
 1&0&0\\
 0&-2&0\\
 0&0&-2
 \end{matrix} \right]
$$

行间公式多为复杂，需要几行来写。希望能修复一下。

3. 其他
在临时开启 miaoyan 外部文件夹时，也会生成 trash 文件夹，有时里面会突然多了一些文档。因为我是用 git 管理，所以突然就多了一堆 untrack file（笑）。希望在开启外部文件夹时，不会自动生成 trash。我个人主要用来看而非编辑，就不知道其他人如何了。
而文件层级，个人建议从 2 层加到 3 层。2 层有些不够，而 3 层加上图书馆分类法则绰绰有余。
当然，这些就一些不成熟的建议，最终还是看作者考量吧。

**Comment by tw93** [comment]
谢谢反馈
👍 你对文本编辑很深入，近期我看看怎么修复哦~

**Comment by tw93** [comment]
@tksze 临时文件夹生成trash文件夹这一块方便给一个视频吗？我试了试没有复现出来这个问题

**Comment by tksze** [comment]
当然。
视频里，用 miaoyan 打开两次。
第一次是打开外部文件夹，md 档案都在其二级文件夹内，会「初始化」该文件夹，即生成介绍文档。
第二次是打开外部 md 文档，正常打开，会在其所在文件夹内生成一个 trash 文件夹（也许这是 feature?)。
第三次我没录，是打开有只有 md 文档的文件夹，正常打开，会生成一个 trash 文件夹。
第四次我也没录，是打开文件夹，其与其二级文件夹都有 md 文档，miaoyan 只能读取一级文件夹，会生成 trash 文件夹。

提议：
1. 除了刚安装应用，或许之后打开其他空文件夹，也不生成介绍文件？
2. 开启外部文件不生成 trash，直接一步到位，扔到系统垃圾桶？

个人认为内部文件管理，这样做没问题，甚至挺方便。但是开启外部文件时，则希望能避免污染。

https://user-images.githubusercontent.com/29708433/180699201-001e3744-3d5c-4532-b5d7-f572cacc7d4e.mov

。

**Comment by tw93** [comment]
`除了刚安装应用，或许之后打开其他空文件夹，也不生成介绍文件？` 这个已经支持，是单独打开模式我没有考虑到
`自动生成垃圾桶` 也已经支持
以及关于 line break  换行设置，均已经在1.1.0版本设置中加入，预计最近会发布
有空辛苦帮我测试一下这个测试包，看看还有没有问题哦
https://gw.alipayobjects.com/os/k/app/MiaoYan%2525202022-07-25%25252023-17-47.zip

![image](https://user-images.githubusercontent.com/8736212/180814461-40dea3df-e43b-4f7f-89a5-0f357061006e.png)

关于公式写的时候不好换行，试试这样是不是OK，我发现是底层markdown解析器转义和latex的一个bug，不是太好解决
```
$$
<span>
D=\left[ \begin{matrix}
 1&0&0\\
 0&-2&0\\
 0&0&-2
 \end{matrix} \right]
$$
</span>
```

**Comment by tksze** [comment]
刚刚测试了。

1. single open 空文件夹时，会「初始化」。
    - 问题已解决，不再生成介绍文档。
2. single open 时，会自动生成 trash 文件夹。
    - 问题已解决，文件删除后直达系统垃圾桶。
3. line break
    - 问题已解决，可自由切换两种 line break 选项。
4. 跨行的行间公式无法渲染
    - 经测试，在 line break 设置成 github 模式下，渲染无问题。之前渲染不了应该和 link break 有关。

幸苦作者了。
基于这条 issue 的问题都已解决，我就在这把它关闭。

**Comment by tw93** [comment]
谢谢你！帮助妙言更好，欢迎尽管提建议

**Comment by tw93** [comment]
正式版本已经发布，可去更新1.1.0 ~
https://github.com/tw93/MiaoYan/releases/tag/V1.1.0
