### ISSUE TITLE
1.0.0版本无法在代码快中输入中文，且在编辑英文字符过程中容易闪退

### ISSUE THREAD

**Issue by elsonz** [tw93/MiaoYan#94]
如：
``` typescript
此处无法输入中文。且容易闪退
```

**Comment by tw93** [comment]
谢谢反馈 晚点我试试

**Comment by elsonz** [comment]
附部分 crash日志：

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000197c371c4
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [89157]

Application Specific Backtrace 0:
0   CoreFoundation                      0x0000000194dd5198 __exceptionPreprocess + 240
1   libobjc.A.dylib                     0x0000000194b1fe04 objc_exception_throw + 60
2   CoreFoundation                      0x0000000194e68f40 -[NSObject(NSObject) __retain_OA] + 0
3   CoreFoundation                      0x0000000194d34544 ___forwarding___ + 1764
4   CoreFoundation                      0x0000000194d33da0 _CF_forwarding_prep_0 + 96
5   UIFoundation                        0x00000001987879d4 -[NSLayoutManager locationForGlyphAtIndex:] + 840
6   UIFoundation                        0x0000000198786a08 -[NSLayoutManager(NSPrivate) _insertionPointHelperForGlyphAtIndex:] + 1184
7   UIFoundation                        0x0000000198786394 _insertionPointHelperForCharacterAtIndex + 1224
8   UIFoundation                        0x0000000198755954 -[NSLayoutManager(NSPrivate) _rectArrayForRange:withinSelectionRange:rangeIsCharRange:singleRectOnly:fullLineRectsOnly:inTextContainer:rectCount:rangeWithinContainer:glyphsDrawOutsideLines:rectArray:rectArrayCapacity:] + 3860
9   UIFoundation                        0x00000001988ef60c -[NSLayoutManager(NSPrivate) _rectArrayForRange:withinSelectionRange:rangeIsCharRange:singleRectOnly:fullLineRectsOnly:inTextContainer:rectCount:rangeWithinContainer:glyphsDrawOutsideLines:] + 56
10  UIFoundation                        0x0000000198754a34 -[NSLayoutManager rectArrayForCharacterRange:withinSelectedCharacterRange:inTextContainer:rectCount:] + 48
11  UIFoundation                        0x0000000198789d34 -[NSLayoutManager(NSPrivate) _drawBackgroundForGlyphRange:atPoint:] + 2356
12  AppKit                              0x0000000197a51c5c -[NSTextView drawRect:] + 1572
13  AppKit                              0x0000000197a13a80 _NSViewDrawRect + 148
14  AppKit                              0x000000019814c1dc -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1308
15  AppKit                              0x0000000197a131f4 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 688
16  AppKit                              0x0000000197a12e88 -[NSView(NSLayerKitGlue) drawLayer:inContext:] + 344
17  AppKit                              0x0000000197b0e384 -[_NSBackingLayerContents drawLayer:inContext:] + 164
18  AppKit                              0x0000000197b0e2ac -[_NSTiledLayer drawTile:inContext:] + 784
19  AppKit                              0x0000000197b0df0c -[_NSTiledLayerContents drawLayer:inContext:] + 220
20  QuartzCore                          0x000000019bbedbf4 CABackingStoreUpdate_ + 484
21  QuartzCore                          0x000000019bc4bee0 ___ZN2CA5Layer8display_Ev_block_invoke + 64
22  QuartzCore                          0x000000019bbecbf8 -[CALayer _display] + 1948
23  AppKit                              0x0000000197b0ddf8 -[NSTileLayer display] + 68
24  AppKit                              0x0000000197b0c650 -[_NSTiledLayerContents update:shouldCallPrepareContent:] + 2992
25  AppKit                              0x0000000197b0b830 -[_NSTiledLayer display] + 320
26  QuartzCore                          0x000000019bbebc4c _ZN2CA5Layer17display_if_neededEPNS_11TransactionE + 780
27  QuartzCore                          0x000000019bd37728 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 464
28  QuartzCore                          0x000000019bbcd44c _ZN2CA11Transaction6commitEv + 704
29  AppKit                              0x0000000197a24910 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 304
30  AppKit                              0x0000000198188c1c ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
31  CoreFoundation                      0x0000000194d54244 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
32  CoreFoundation                      0x0000000194d54094 __CFRunLoopDoObservers + 592
33  CoreFoundation                      0x0000000194d535c8 __CFRunLoopRun + 772
34  CoreFoundation                      0x0000000194d52b24 CFRunLoopRunSpecific + 600
35  HIToolbox                           0x000000019d98b338 RunCurrentEventLoopInMode + 292
36  HIToolbox                           0x000000019d98b0b4 ReceiveNextEventCommon + 564
37  HIToolbox                           0x000000019d98ae68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
38  AppKit                              0x00000001978b978c _DPSNextEvent + 860
39  AppKit                              0x00000001978b8084 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
40  AppKit                              0x00000001978aa250 -[NSApplication run] + 596
41  AppKit                              0x000000019787b96c NSApplicationMain + 1132
42  MiaoYan                             0x0000000100f477e8 main + 12
43  dyld                                0x000000010175508c start + 520

**Comment by tw93** [comment]
你好 方便录制一个视频吗？我这边试了试没有复现出来，此外你用的啥输入法？之前鼠须管记得有些问题

**Comment by elsonz** [comment]
https://user-images.githubusercontent.com/9108871/180611560-5b91bb04-243c-41f5-9ecb-654bfca36d9f.mp4

mac 自带的拼音输入法
crash不太好复现。

**Comment by tw93** [comment]
好的 谢谢反馈，我去复现复现

**Comment by tw93** [comment]
深度使用了两天这个功能，还是没有复现，这样等下次我复现了再来修复好啦，希望理解~
