### ISSUE TITLE
how to export a md file as a PPT?

### ISSUE THREAD

**Issue by shiboshibo** [tw93/MiaoYan#95]
is there any idea about how to export a ppt file?

**Comment by tw93** [comment]
Temporarily not supported. You can export ordinary pdf and ppt. I want to realize the next version.

**Comment by tw93** [comment]
It has been supported. You can try this test version first. The official version 1.1.0 will be released in a few days.

[download](https://gw.alipayobjects.com/os/k/app/MiaoYan%2525202022-07-26%25252022-55-44.zip)

![image](https://user-images.githubusercontent.com/8736212/181039867-b4c05344-033d-4562-809b-0db3d170315c.png)

**Comment by shiboshibo** [comment]
Thank you,l'll try





------------------ Original ------------------
From: Tw93 ***@***.***&gt;
Date: Tue,Jul 26,2022 11:02 PM
To: tw93/MiaoYan ***@***.***&gt;
Cc: shibo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [tw93/MiaoYan] how to export a md file as a PPT? (Issue #95)





 
It has been supported. You can try this test version first. The official version 1.1.0 will be released in a few days.
 
download

**Comment by tw93** [comment]
The official version has been released. You can update 1.1.0~
https://github.com/tw93/MiaoYan/releases/tag/V1.1.0
