### ISSUE TITLE
1.0.0版本预览``颜色

### ISSUE THREAD

**Issue by cnxiekun** [tw93/MiaoYan#98]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/21699650/180935550-d2301d9a-86c0-4a79-b31c-c5ac21128c1c.png">
<img width="907" alt="image" src="https://user-images.githubusercontent.com/21699650/180935578-d42de38f-3cbd-470f-a109-06f2f5832ee5.png">

在列表里面的 `` 显示的bug?

**Comment by tw93** [comment]
谢谢反馈，的确是bug，我修复一下

**Comment by tw93** [comment]
辛苦去更新，1.1.1，直接点击妙言菜单栏检查更新即可~
