### ISSUE TITLE
列表中使用代码块时，预览颜色异常

### ISSUE THREAD

**Issue by shellRaining** [tw93/MiaoYan#99]
如图
<img width="344" alt="image" src="https://user-images.githubusercontent.com/72488394/181231758-f9ce8c51-31fe-4282-be21-323f6723ef26.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/72488394/181231781-df6a3a9a-8f22-4274-83b2-c9880bb5f2df.png">

无序列表和有序列表均会出现此情况
似乎和 #98 是一个问题

**Comment by shellRaining** [comment]
使用三个反引号的代码块也会出现该情况

**Comment by tw93** [comment]
@shellRaining 试试98中的测试包

**Comment by shellRaining** [comment]
> @shellRaining 试试98中的测试包

 OK，这个版本是没有问题的

**Comment by tw93** [comment]
正式版本已经发布，可去更新1.1.0 ~
https://github.com/tw93/MiaoYan/releases/tag/V1.1.0
